; changes/278-rtlintegertounicodestring/impl.asm
;   NTSTATUS wia_int2ustr(ULONG value, ULONG base, UNICODE_STRING* out)
;       [Win64: ecx, edx, r8 -> eax]
;
; ntdll!RtlIntegerToUnicodeString. discovery/rtl_integer_char.c measured it at 32.14 ns for ten
; decimal digits, 18.66 for eight hexadecimal, 20.35 for eleven octal and 40.27 for thirty-two
; binary, and 10.16 ns for a SINGLE DIGIT. Change 067's rewritten formatter does a whole 32-bit
; number in 3.76 ns, and the division-per-digit version it replaced took 12.77.
;
; The per-base spread is the tell: thirty-two binary digits costing only twice what ten decimal
; digits costs, while ONE digit still costs 10 ns, says the cost is mostly fixed and partly
; per-digit, a division loop behind a validation prologue.
;
; --------------------------------------------------------------------------------------------------
; THE CONTRACT, measured in probes/contract.c and not assumed from the documentation:
;
;   1. Only bases 0, 2, 8, 10 And 16 Are accepted, and 0 means 10. Every other value from 1 to
;      0xFFFFFFFF (including 4, 32 and 36) is STATUS_INVALID_PARAMETER. The sweep asked 0..20
;      one at a time rather than trusting the documented set.
;   2. No prefix, and the hexadecimal digits are uppercase. Zero is "0" in every base.
;   3. The room rule is MaximumLength >= Length + 2. Not Length+1, and that is worth saying,
;      because change 067 found the analogous rule in RtlConvertSidToUnicodeString IS Length+1, and
;      at exactly Length+1 that one writes no terminator at all. Two routines in the same DLL, two
;      different rules; the only way to know which is which is to ask each.
;   4. a terminator is always written, inside MaximumLength, and Length excludes it.
;   5. On any failure the destination is completely untouched, not Length, not one character.
;   6. The value is UNSIGNED: 0xFFFFFFFF is "4294967295", never "-1".
;
; --------------------------------------------------------------------------------------------------
; The implementation is two converters, both length-first.
;
; Knowing the length before writing anything is what removes the scratch buffer and the reversal
; pass that a digit-at-a-time loop needs, change 067's finding, and the reason its rewrite was
; worth 3.4x on the number itself.
;
;   BASE 10 is change 067's method: digits10 from one BSR, a byte from a table indexed by the bit
;   length and one compare against a power of ten; then the digits are emitted two at a time,
;   backwards, as a single dword store from a table of pre-packed UTF-16 pairs, dividing by 100 with
;   a multiply. probes/decimal.c in change 067 proved (v * 51EB851Fh) >> 37 == v/100 for all
;   4294967296 values of v, and digits10 exact over the same domain.
;
;   BASES 2, 8 AND 16 share one loop, because they are all powers of two: the shift is BSR(base) --
;   1, 3 and 4; the mask is base-1, and the digit count comes from a table indexed by the shift
;   and the bit length. One digit per iteration, from the bottom up, straight into the destination.
;
; Every table is generated by the assembler from the definition it is supposed to satisfy, and
; correctness.c checks all five back against those definitions, change 267's first table
; construction was wrong.
;
; ISA: baseline x64. There is nothing to vectorise in a number at most thirty-two digits long.

OPTION PROC:PRIVATE
PUBLIC wia_int2ustr
PUBLIC wia_i2u_tables                       ; so correctness.c can check them

ST_INVALID EQU 0C000000Dh                   ; STATUS_INVALID_PARAMETER
ST_OVERFLOW EQU 80000005h                   ; STATUS_BUFFER_OVERFLOW

.const
ALIGN 16
; DEC2W[i] is i in decimal, two characters, packed little-endian as UTF-16.
DEC2W   LABEL DWORD
        NI = 0
        REPT 100
          DD (30h + (NI / 10)) OR ((30h + (NI MOD 10)) SHL 16)
          NI = NI + 1
        ENDM

ALIGN 16
TABS    LABEL QWORD
POW10   LABEL QWORD                          ; +0   : 10^0 .. 10^10, qwords because 10^10 > 2^32
        NP = 1
        REPT 11
          DQ NP
          NP = NP * 10
        ENDM
GTAB    LABEL BYTE                           ; +88  : digits10(2^B) = (B*1233)/4096 + 1
        NB = 0
        REPT 32
          DB (NB * 1233) / 4096 + 1
          NB = NB + 1
        ENDM
HEXCH   LABEL BYTE                           ; +120 : uppercase, because the live export is
        DB      '0123456789ABCDEF'
; +136 : five rows of 32 bytes. Row S holds, for each bit length B, how many base-2^S digits a value
; of that bit length needs, B/S + 1. Only rows 1, 3 and 4 are ever indexed, because the shift is
; BSR(base) and the base has already been checked to be 2, 8 or 16; rows 0 and 2 are padding that
; keeps the row index a plain shift.
DIGP2   LABEL BYTE
        NS = 0
        REPT 5
          NB2 = 0
          REPT 32
            IF NS EQ 0
              DB 1
            ELSE
              DB (NB2 / NS) + 1
            ENDIF
            NB2 = NB2 + 1
          ENDM
          NS = NS + 1
        ENDM

GOFF    EQU 88
HOFF    EQU 120
POFF    EQU 136

.code

ALIGN 16
wia_int2ustr PROC
        ; rcx = value, edx = base, r8 = the UNICODE_STRING. A leaf: nothing is saved, nothing is
        ; pushed, and there are no calls at all.
        mov       r10d, ecx                       ; the value
        test      edx, edx
        jnz       have_base
        mov       edx, 10                         ; base 0 means base 10
have_base:
        cmp       edx, 10
        je        base10
        cmp       edx, 16
        je        pow2
        cmp       edx, 8
        je        pow2
        cmp       edx, 2
        je        pow2
        mov       eax, ST_INVALID
        ret

; ---------------------------------------------------------------- the power-of-two bases
pow2:
        lea       r11, TABS
        bsr       ecx, edx                        ; the shift: 1, 3 or 4
        mov       r9d, r10d
        or        r9d, 1                          ; BSR is undefined at zero; "0" is one digit
        bsr       r9d, r9d                        ; the bit length
        shl       ecx, 5                          ; the row for this shift
        add       ecx, r9d
        movzx     r9d, byte ptr [r11 + POFF + rcx]   ; how many digits
        ; room: Length + 2, measured
        lea       eax, [r9d*2 + 2]
        movzx     ecx, word ptr [r8 + 2]          ; MaximumLength
        cmp       ecx, eax
        jb        overflow
        mov       ecx, r9d
        shl       ecx, 1
        mov       word ptr [r8], cx               ; Out->Length, the terminator excluded
        mov       rax, qword ptr [r8 + 8]         ; Out->Buffer
        lea       rax, [rax + rcx]                ; one past the last character
        mov       word ptr [rax], 0               ; the terminator, inside MaximumLength
        lea       r11, HEXCH
        mov       r9d, edx
        dec       r9d                             ; the mask: base - 1
        bsr       ecx, edx                        ; the shift, in CL because SHR needs it there
p2_next:
        mov       edx, r10d
        and       edx, r9d
        movzx     edx, byte ptr [r11 + rdx]
        sub       rax, 2
        mov       word ptr [rax], dx
        shr       r10d, cl
        jnz       p2_next                         ; the digit count was exact, so this lands on
                                                  ; Buffer and writes every digit once
        xor       eax, eax
        ret

; ---------------------------------------------------------------- base ten
base10:
        lea       r11, TABS
        mov       ecx, r10d
        or        ecx, 1
        bsr       ecx, ecx
        movzx     r9d, byte ptr [r11 + GOFF + rcx]
        mov       eax, r10d
        cmp       rax, qword ptr [r11 + r9*8]
        setae     cl
        movzx     ecx, cl
        add       r9d, ecx                        ; digits10(value)
        lea       eax, [r9d*2 + 2]
        movzx     ecx, word ptr [r8 + 2]
        cmp       ecx, eax
        jb        overflow
        mov       ecx, r9d
        shl       ecx, 1
        mov       word ptr [r8], cx
        mov       rax, qword ptr [r8 + 8]
        lea       rax, [rax + rcx]
        mov       word ptr [rax], 0
        lea       r11, DEC2W
b10_pairs:
        cmp       r9d, 2
        jb        b10_last
        mov       edx, r10d
        imul      rdx, rdx, 51EB851Fh
        shr       rdx, 37                         ; value / 100, exact over all 2^32
        imul      ecx, edx, 100
        sub       r10d, ecx                       ; the remainder, 0..99
        mov       ecx, dword ptr [r11 + r10*4]
        sub       rax, 4
        mov       dword ptr [rax], ecx            ; two characters, one store
        mov       r10d, edx
        sub       r9d, 2
        jmp       b10_pairs
b10_last:
        test      r9d, r9d
        jz        b10_done
        add       r10d, 30h
        sub       rax, 2
        mov       word ptr [rax], r10w
b10_done:
        xor       eax, eax
        ret

overflow:
        mov       eax, ST_OVERFLOW
        ret
wia_int2ustr ENDP

ALIGN 16
wia_i2u_tables PROC
        lea       rax, DEC2W
        ret
wia_i2u_tables ENDP

END
