; ws2_32.dll!inet_ntoa  --  hand-written x86-64 reimplementation (3.24x vs shipped)
; source of truth: changes/275-inet-ntoa/  (reference.c + correctness.c + bench.c)
; validated bit-exact vs the live export; see that dir's RESULTS.md.
;----------------------------------------------------------------------
; changes/275-inet-ntoa/impl.asm
;   char* wia_inet_ntoa(unsigned long in)      [Win64: ecx -> rax]
;
; ws2_32!inet_ntoa. The argument is `struct in_addr` BY VALUE, which is four bytes, so Win64 passes
; it in ecx as an integer -- the four address bytes in memory order are the four bytes of ecx from
; the bottom up.
;
; --------------------------------------------------------------------------------------------------
; The text is "%u.%u.%u.%u" of the four bytes, and that is measured rather than assumed:
; probes/contract.c compares the export against wsprintfA for every one of the 256 byte values in
; EACH of the four positions -- all 1024 combinations -- with zero disagreements.
;
; The answer goes in a per-thread buffer. The same pointer on every call from one thread, a
; different one per thread, undisturbed by inet_addr, htonl, WSAGetLastError or inet_ntop. The
; caller owns nothing and the text is valid until that thread calls again. tls.c owns that buffer and
; says why the access is the compiler's.
;
; --------------------------------------------------------------------------------------------------
; Why this change exists when 274 Is parked. probes/floor.c timed four things per call:
;
;     ws2_32!inet_ntoa                    7.47 ns
;     C, wsprintfA                       22.12 ns     the naive replacement, for scale
;     C, the digit table                  1.43 ns     what the assembly below does
;     the TLS access alone                0.38 ns     the floor every implementation pays
;
; 1.43 against 7.47 with a floor of 0.38 is a real margin, where change 274's short rows were a
; 15 ns allocator call with 0.3 ns of our work inside them. The question was asked the same way both
; times; here the answer came back yes.
;
; --------------------------------------------------------------------------------------------------
; One dword store per field. The table holds every value 0..255 already rendered, with its trailing
; DOT, packed into four bytes -- "7." , "42." , "255." -- and a second table holds how far to step.
; So a field costs a table load, an unaligned four-byte store and an add, and the dots come free
; because they are part of the rendering. The last dot is then overwritten with the terminator,
; which is why the step tables include it.
;
; Both tables are generated by the assembler from the definition they are supposed to satisfy, and
; correctness.c checks them back against it -- change 267's first table construction was wrong.
;
; ISA: baseline x64.

OPTION PROC:PRIVATE
PUBLIC wia_inet_ntoa
PUBLIC wia_ntoa_tables                      ; so correctness.c can check them

EXTERN wia_ntoa_buf:PROC                    ; the per-thread buffer -- see tls.c

.const
ALIGN 16
; DOT4[i] is i in decimal followed by '.', little-endian, padded with zeros.
DOT4    LABEL DWORD
        NI = 0
        REPT 256
          IF NI LT 10
            DD (30h + NI) OR (2Eh SHL 8)
          ELSEIF NI LT 100
            DD (30h + (NI / 10)) OR ((30h + (NI MOD 10)) SHL 8) OR (2Eh SHL 16)
          ELSE
            DD (30h + (NI / 100)) OR ((30h + ((NI / 10) MOD 10)) SHL 8) OR \
               ((30h + (NI MOD 10)) SHL 16) OR (2Eh SHL 24)
          ENDIF
          NI = NI + 1
        ENDM

; DLEN[i] is how far to step: the digits AND the dot.
DLEN    LABEL BYTE
        NJ = 0
        REPT 256
          IF NJ LT 10
            DB 2
          ELSEIF NJ LT 100
            DB 3
          ELSE
            DB 4
          ENDIF
          NJ = NJ + 1
        ENDM

.code

FRAME_SZ  EQU 32                            ; shadow space for the one call out

ALIGN 16
wia_inet_ntoa PROC FRAME
        push      rbx
        .pushreg  rbx
        sub       rsp, FRAME_SZ
        .allocstack FRAME_SZ
        .endprolog

        mov       ebx, ecx                        ; the four address bytes
        call      wia_ntoa_buf
        mov       r11, rax                        ; the buffer, and the return value
        mov       rdx, rax                        ; the write pointer
        lea       r8, DOT4
        lea       r9, DLEN

        movzx     ecx, bl
        mov       eax, dword ptr [r8 + rcx*4]
        mov       dword ptr [rdx], eax
        movzx     eax, byte ptr [r9 + rcx]
        add       rdx, rax

        shr       ebx, 8
        movzx     ecx, bl
        mov       eax, dword ptr [r8 + rcx*4]
        mov       dword ptr [rdx], eax
        movzx     eax, byte ptr [r9 + rcx]
        add       rdx, rax

        shr       ebx, 8
        movzx     ecx, bl
        mov       eax, dword ptr [r8 + rcx*4]
        mov       dword ptr [rdx], eax
        movzx     eax, byte ptr [r9 + rcx]
        add       rdx, rax

        shr       ebx, 8
        movzx     ecx, bl
        mov       eax, dword ptr [r8 + rcx*4]
        mov       dword ptr [rdx], eax
        movzx     eax, byte ptr [r9 + rcx]
        add       rdx, rax

        mov       byte ptr [rdx - 1], 0           ; the fourth dot becomes the terminator
        mov       rax, r11
        add       rsp, FRAME_SZ
        pop       rbx
        ret
wia_inet_ntoa ENDP

ALIGN 16
wia_ntoa_tables PROC
        lea       rax, DOT4
        ret
wia_ntoa_tables ENDP

END
