/* changes/282-strrchriw/probes/nulchar.c
 *
 * Which needles match a NUL *character*? Change 281 Could not ask.
 *
 * Change 281 extracted the whole match relation from the live export by searching a haystack that
 * contained every code unit 1..65535. It could not contain a NUL: StrChrIW stops at the terminator,
 * so a NUL in the haystack would have ended every search. The relation it produced is therefore
 * complete except for one column (what matches the code unit ZERO) and that column is
 * unreachable through StrChrIW by construction.
 *
 * StrRChrIW has no terminator. Its range is explicit, embedded NULs are ordinary characters
 * (probes/bounds.c: "abcd\0fghijk" with end = start+11 finds 'J' at index 9), so it can be asked.
 * Change 282's gate asked it immediately: 21 mismatches, every one needle 0 against a planted NUL,
 * ours and the model saying NULL while the live export found it.
 *
 * This is the same failure mode as change 281's probes/contract.c and as changes 097 and 100: a
 * corpus that could not express the case. The difference is where it sat, not in the test, but in
 * the EXTRACTION METHOD, which is a place worth remembering to look.
 *
 * So: for every code unit, ask StrRChrIW whether it finds a lone NUL. Writes foldnul.c.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>

typedef PCWSTR (WINAPI *F_rchr)(PCWSTR, PCWSTR, WCHAR);

int main(void)
{
    HMODULE hs = LoadLibraryW(L"shlwapi.dll");
    F_rchr f = hs ? (F_rchr)GetProcAddress(hs, "StrRChrIW") : 0;
    static wchar_t z[2];
    static unsigned short hit[65536];
    unsigned c;
    long n = 0, shown = 0;
    FILE* out;

    setvbuf(stdout, NULL, _IONBF, 0);
    if (!f) { printf("resolve failed\n"); return 1; }
    z[0] = 0; z[1] = 0;

    printf("== which needles find a lone NUL character? ==\n");
    for (c = 0; c <= 0xFFFF; ++c) {
        if (f(z, z + 1, (WCHAR)c)) {
            hit[n++] = (unsigned short)c;
            if (shown < 24) { printf(" %04X", c); if ((++shown % 12) == 0) printf("\n"); }
        }
    }
    printf("\n\n   %ld of 65536 needles match a NUL character\n", n);

    /* and the converse: does the NUL needle match those same characters? the relation is symmetric
       for every pair change 281 could reach, so this is a check on that expectation, not a guess */
    {
        long asym = 0;
        unsigned k;
        for (k = 0; k < (unsigned)n && k < 4000; ++k) {
            wchar_t one[2];
            one[0] = (wchar_t)hit[k]; one[1] = 0;
            if (!f(one, one + 1, 0)) ++asym;
        }
        printf("   of the first %u of them, %ld are NOT found by the NUL needle (asymmetry)\n",
               (unsigned)(n < 4000 ? n : 4000), asym);
    }

    out = fopen("../../281-strchriw/foldnul.c", "w");
    if (!out) { printf("cannot write ../foldnul.c\n"); return 1; }
    fprintf(out,
"/* changes/282-strrchriw/foldnul.c -- GENERATED by probes/nulchar.c. Do not edit by hand.\n"
" *\n"
" * THE COLUMN CHANGE 281 COULD NOT REACH: which needles match the code unit ZERO.\n"
" *\n"
" * 281 extracted the match relation by searching a haystack holding every code unit 1..65535. That\n"
" * haystack could not contain a NUL, because StrChrIW stops at the terminator -- so what matches\n"
" * code unit 0 was unreachable by construction, and the tables say nothing about it. StrRChrIW has\n"
" * no terminator and can be asked; change 282's gate found the gap at once, 21 mismatches where\n"
" * the live export found a planted NUL and both our sides said NULL.\n"
" *\n"
" * %ld of the 65536 needles match a NUL character. tables_nul.c folds them into change 281's\n"
" * tables at init and re-checks them against the live export.\n"
" */\n"
"const unsigned short wia_sci_nulhit[] = {\n", n);
    {
        long i;
        for (i = 0; i < n; ++i) {
            fprintf(out, "0x%04X,", hit[i]);
            if ((i % 12) == 11) fprintf(out, "\n");
        }
    }
    fprintf(out, "};\nconst unsigned wia_sci_nnulhit = %ld;\n", n);
    fclose(out);
    printf("   wrote ../../281-strchriw/foldnul.c\n");
    return 0;
}
