; changes/067-rtlconvertsidtounicodestring/impl.asm
; NTSTATUS wia_sidfmt(UNICODE_STRING* Out, void* Sid, BOOLEAN Allocate)
;   [Win64: rcx=Out, rdx=Sid, r8b=Allocate -> eax]   (Allocate=FALSE path)
;
; ntdll!RtlConvertSidToUnicodeString, caller-buffer form. Format a SID as
; "S-<rev>-<authority>-<subauth>-..." where the 48-bit identifier authority is DECIMAL when it fits
; in 32 bits and otherwise "0x" + minimal UPPERCASE hex, and each sub-authority is unsigned 32-bit
; decimal. The revision must be 1 and the sub-authority count at most 15, else STATUS_INVALID_SID
; (0xC0000078). Writes the string and a NUL, sets Out->Length, and needs MaximumLength >= Length+2
; else STATUS_BUFFER_OVERFLOW (0x80000005) with Out UNTOUCHED.
;
; --------------------------------------------------------------------------------------------------
; What this function is: Fifteen number conversions and a copy. Nothing else is on the critical
; path, so the only thing that matters is what one 32-bit number costs.
;
; The first version of this file cost a division per digit:
;
;     dul:    xor  edx, edx
;             div  ecx                 ; ecx = 10
;             add  dl, 30h
;             mov  byte ptr [r10], dl  ; ... into a scratch, read back in reverse afterwards
;
; A sub-authority such as 2596069104 is ten digits, so it was ten dependent 32-bit divisions and
; then a second pass to reverse the bytes into wide characters. probes/decimal.c measures that at
; 12.77 ns per ten-digit number against 3.76 ns for the form below, and since a five-sub-authority
; SID is seven numbers, essentially the whole of this function was `div`. The file even declared
; `EXTERN wia_dec2b`, the two-digit table changes 054 and 202 use, and then never referenced it.
;
; The form below does three things differently:
;
;   1. It divides by 100, with a multiply.  q = (v * 51EB851Fh) >> 37, in 64 bits.
;   2. It knows the length first, so the characters go straight into the destination backwards and
;      there is no scratch buffer and no reversal pass. digits10(v) is one BSR, one byte from a
;      table indexed by the bit length, and one compare against a power of ten.
;   3. It emits two characters per iteration, as a single dword store out of a 100-entry table of
;      pre-packed UTF-16 pairs.
;
; Neither constant is quoted. probes/decimal.c checks (v * 51EB851Fh) >> 37 against the compiler's
; own division, and digits10 against the compiler's own loop, for ALL 4294967296 values of v: zero
; counterexamples each. A magic constant that is right for 99.9999% of its domain is a defect no
; random corpus finds, which is the standard change 267 applied to its GF(2) shift tables, and the
; first draft of THOSE was wrong.
;
; Every table is generated by the assembler from the definition it is supposed to satisfy, rather
; than typed out: the digit pairs from I/10 and I MOD 10, the powers of ten from a running multiply,
; and the bit-length-to-digit-count table from (B*1233)/4096 + 1. A transcribed table is a constant
; nobody can check by reading it.
;
; And it is now a `proc frame`. The first version was a bare proc with five pushes, a 480-byte frame
; and `call du` inside the body, so it had no unwind data at all, and an exception raised anywhere
; underneath it could not be unwound through. Everything is inlined through macros now, nothing is
; pushed in the body and nothing is called from it, which is what makes the unwind data expressible.
;
; ISA: AVX2 for the final copy (a 32-byte chunked move with an overlapping last chunk, so the
; destination is written exactly Length+2 bytes and never one more); the rest is baseline x64.

OPTION PROC:PRIVATE
PUBLIC wia_sidfmt
PUBLIC wia_sidfmt_dec2w                     ; exported so correctness.c can check the tables
PUBLIC wia_sidfmt_tabs

EXTERN wia_sid_header:PROC                  ; the protected header read -- see probe.c

; --------------------------------------------------------------------------------------------------
.const
ALIGN 16
; 100 pre-packed pairs of UTF-16 characters: entry I is the two characters of I, tens first.
DEC2W   LABEL DWORD
        PKI = 0
        REPT 100
          DD (30h + (PKI / 10)) OR ((30h + (PKI MOD 10)) SHL 16)
          PKI = PKI + 1
        ENDM

ALIGN 16
; One block, one base register: the powers of ten, then the bit-length table, then the hex digits.
TABS    LABEL QWORD
POW10   LABEL QWORD                          ; +0   : 10^0 .. 10^10, as qwords because 10^10 > 2^32
        PKP = 1
        REPT 11
          DQ PKP
          PKP = PKP * 10
        ENDM
GTAB    LABEL BYTE                           ; +88  : digits10(2^B), which is (B*1233)/4096 + 1
        PKB = 0
        REPT 32
          DB (PKB * 1233) / 4096 + 1
          PKB = PKB + 1
        ENDM
HEXCH   LABEL BYTE                           ; +120 : uppercase, because the live export is
        DB      '0123456789ABCDEF'

GOFF    EQU 88
HOFF    EQU 120

; --------------------------------------------------------------------------------------------------
; The frame: 32 bytes of shadow space for the one call out, then the temporary string. 552 rather
; than 544 so that rsp is 16-byte aligned at the call site, eight pushes leave it 8 off.
TMP       EQU 32
FRAME_SZ  EQU 552                            ; the temporary string: 184 characters is the longest

; DECW, one unsigned 32-bit number, in decimal, written into [rdi] and rdi advanced past it.
;
;   in    eax = the value, rdi = the destination, rbp = DEC2W, r14 = TABS
;   out   rdi advanced by 2*digits10(value)
;   uses  rax rcx rdx r10 r11
;
; The length comes first so the pairs can be written backwards straight into the destination. That
; is the whole trick: no scratch, no reversal, and one store per two characters.
DECW MACRO
        LOCAL   pairs, last, fin
        mov       ecx, eax
        or        ecx, 1                          ; BSR is undefined at zero; "0" has one digit
        bsr       ecx, ecx                        ; floor(log2(v|1)), 0..31
        movzx     r10d, byte ptr [r14 + GOFF + rcx]
        mov       r11d, eax                       ; zero-extended, for a 64-bit compare
        cmp       r11, qword ptr [r14 + r10*8]
        setae     cl
        movzx     ecx, cl
        add       r10d, ecx                       ; n = digits10(v); the table is never off by more
        lea       r11, [rdi + r10*2]              ; one past the last character
        mov       rdi, r11                        ; ... which is where rdi ends up
pairs:  cmp       r10d, 2
        jb        last
        mov       edx, eax
        imul      rdx, rdx, 51EB851Fh
        shr       rdx, 37                         ; q = v / 100, proved exact over all 2^32
        imul      ecx, edx, 100
        sub       eax, ecx                        ; r = v - 100q, in 0..99
        mov       ecx, dword ptr [rbp + rax*4]
        mov       dword ptr [r11 - 4], ecx        ; two characters, one store
        sub       r11, 4
        mov       eax, edx
        sub       r10d, 2
        jmp       pairs
last:   test      r10d, r10d
        jz        fin
        add       eax, 30h
        mov       word ptr [r11 - 2], ax
fin:
        ENDM

; HEXW, the 48-bit identifier authority in minimal uppercase hex, written into [rdi].
;
;   in    rax = the value (non-zero above 32 bits, so at least nine nibbles), rdi, r14 = TABS
;   uses  rax rcx rdx r10 r11
;
; Written backwards for the same reason, a nibble at a time: this path needs an identifier authority
; of 2^32 or more, which no SID in ordinary use has, so there is nothing to win by pairing it.
HEXW MACRO
        LOCAL   nib
        bsr      rcx, rax
        shr      ecx, 2
        inc      ecx                              ; nibbles = floor(log2 v)/4 + 1
        lea      r11, [rdi + rcx*2]
        mov      rdi, r11
nib:    mov      edx, eax
        and      edx, 0Fh
        movzx    edx, byte ptr [r14 + HOFF + rdx]
        mov      word ptr [r11 - 2], dx
        sub      r11, 2
        shr      rax, 4
        jnz      nib
        ENDM

; --------------------------------------------------------------------------------------------------
.code

ALIGN 16
wia_sidfmt PROC FRAME
        push      rbx
        .pushreg  rbx
        push      rsi
        .pushreg  rsi
        push      rdi
        .pushreg  rdi
        push      rbp
        .pushreg  rbp
        push      r12
        .pushreg  r12
        push      r13
        .pushreg  r13
        push      r14
        .pushreg  r14
        push      r15
        .pushreg  r15
        sub       rsp, FRAME_SZ
        .allocstack FRAME_SZ
        .endprolog

        mov       rbx, rcx                        ; Out*
        mov       rsi, rdx                        ; Sid

        ; The revision, the count and the last sub-authority are read under an exception handler,
        ; and the six identifier-authority bytes are not. That is not a choice; it is what the live
        ; export does, measured with a guard page in changes/270-.../probes/truncated.c and
        ; explained in probe.c. A short SID is a REFUSAL when its sub-authority array runs off the
        ; end and a FAULT when only its authority does.
        mov       rcx, rsi
        call      wia_sid_header
        test      eax, eax
        js        bad_sid                         ; -1: the header could not be read
        mov       r13d, eax
        shr       r13d, 8                         ; the sub-authority count
        and       eax, 0FFh
        cmp       eax, 1
        jne       bad_sid                         ; the revision must be 1
        cmp       r13d, 15
        ja        bad_sid

        lea       rbp, DEC2W
        lea       r14, TABS
        lea       rdi, [rsp + TMP]                ; the temporary string

        ; One load for the rest of the header. After the byte swap rax holds, from the top down,
        ; revision, count, and the six identifier-authority bytes in the order they are written --
        ; which is the order they are printed in, because the authority is big-endian in the
        ; structure. This load is the UNPROTECTED one, and it is the one the live export faults on.
        mov       rax, qword ptr [rsi]
        bswap     rax
        mov       r12, rax                        ; keep the swapped header

        mov       dword ptr [rdi], 002D0053h      ; 'S' '-'
        add       rdi, 4
        mov       eax, 1                          ; the revision, which is 1 and prints as one digit
        DECW
        mov       word ptr [rdi], '-'
        add       rdi, 2

        ; the identifier authority: decimal below 2^32, else "0x" and uppercase hex
        mov       rax, r12
        mov       rcx, rax
        shr       rcx, 32
        and       ecx, 0FFFFh                     ; the top two of its six bytes
        jnz       auth_hex
        DECW
        jmp       auth_done
auth_hex:
        mov       dword ptr [rdi], 00780030h      ; '0' 'x'
        add       rdi, 4
        mov       rax, r12
        mov       rcx, 0FFFFFFFFFFFFh
        and       rax, rcx
        HEXW
auth_done:

        xor       r15d, r15d
sa_loop:
        cmp       r15d, r13d
        jae       sa_done
        mov       word ptr [rdi], '-'
        add       rdi, 2
        mov       eax, dword ptr [rsi + 8 + r15*4]
        DECW
        inc       r15d
        jmp       sa_loop
sa_done:
        mov       word ptr [rdi], 0               ; the NUL, in the temporary

        lea       rdx, [rsp + TMP]
        mov       r9, rdi
        sub       r9, rdx                         ; Length, in bytes, without the NUL
        movzx     edx, word ptr [rbx + 2]         ; MaximumLength

        ; The room rule is Length+1, and at exactly Length+1 no terminator is written. Not
        ; Length+2, which is what "the terminator is a wide character" suggests and what this file
        ; used to do. probes/oddroom.c measured every MaximumLength around the boundary at three
        ; lengths: at Length+1 the string and Out->Length go in and the two bytes past the string
        ; keep the caller's fill; at Length+2 a full wide NUL appears. The old gate stepped
        ; MaximumLength by TWO, so the entire boundary was unreachable by its corpus.
        lea       r10d, [r9d + 1]
        cmp       edx, r10d
        jb        overflow                        ; Out is left completely untouched
        mov       word ptr [rbx], r9w             ; Out->Length
        mov       r10d, r9d                       ; move the string ...
        lea       ecx, [r9d + 2]
        cmp       edx, ecx
        jb        no_nul
        mov       r10d, ecx                       ; ... and the terminator, if it fits
no_nul:
        mov       rdi, qword ptr [rbx + 8]        ; Out->Buffer
        lea       rsi, [rsp + TMP]
        mov       r9d, r10d                       ; bytes to move

        ; Exactly r9d bytes and never one more. The destination is only guaranteed to hold
        ; Length+2, so the tail is an OVERLAPPING chunk from the end rather than a rounded-up one --
        ; the same rule change 016 had to be corrected for, where storing sixteen bytes and
        ; advancing by fewer left zeros past the end of the string that change 268's whole-buffer
        ; comparison caught. The shortest possible result is "S-1-0" and a NUL, twelve bytes, so the
        ; eight-byte path below always has something to work with.
        cmp       r9d, 32
        jb        cp_small
        xor       ecx, ecx
cp32:   vmovdqu   ymm0, ymmword ptr [rsi + rcx]
        vmovdqu   ymmword ptr [rdi + rcx], ymm0
        add       ecx, 32
        lea       edx, [ecx + 32]
        cmp       edx, r9d
        jbe       cp32
        mov       edx, r9d
        sub       edx, 32
        vmovdqu   ymm0, ymmword ptr [rsi + rdx]
        vmovdqu   ymmword ptr [rdi + rdx], ymm0
        vzeroupper
        jmp       cp_done
cp_small:
        xor       ecx, ecx
cp8:    mov       rax, qword ptr [rsi + rcx]
        mov       qword ptr [rdi + rcx], rax
        add       ecx, 8
        lea       edx, [ecx + 8]
        cmp       edx, r9d
        jbe       cp8
        mov       edx, r9d
        sub       edx, 8
        mov       rax, qword ptr [rsi + rdx]
        mov       qword ptr [rdi + rdx], rax
cp_done:
        xor       eax, eax                        ; STATUS_SUCCESS
        jmp       epi
overflow:
        mov       eax, 80000005h                  ; STATUS_BUFFER_OVERFLOW
        jmp       epi
bad_sid:
        mov       eax, 0C0000078h                 ; STATUS_INVALID_SID
epi:
        add       rsp, FRAME_SZ
        pop       r15
        pop       r14
        pop       r13
        pop       r12
        pop       rbp
        pop       rdi
        pop       rsi
        pop       rbx
        ret
wia_sidfmt ENDP

; The two tables, so that correctness.c can check them against the definitions they are supposed to
; satisfy rather than trusting the assembler arithmetic that produced them.
ALIGN 16
wia_sidfmt_dec2w PROC
        lea       rax, DEC2W
        ret
wia_sidfmt_dec2w ENDP

ALIGN 16
wia_sidfmt_tabs PROC
        lea       rax, TABS
        ret
wia_sidfmt_tabs ENDP

END
