; changes/034-rtlutf8tounicoden/impl.asm
; NTSTATUS wia_u82u(wchar_t* dst, ULONG maxBytes, PULONG outLen, const void* src, ULONG srcBytes)
;   [Win64: rcx, edx, r8, r9, [rsp+0x28] -> eax; *outLen = bytes produced]
;
; Reimplements ntdll!RtlUTF8ToUnicodeN (UTF-8 -> UTF-16). Full decoder validated
; in C against the live ntdll oracle (0 mismatches / 400000, incl. every malformed
; class). Malformed input follows the Unicode maximal-subpart rule with ntdll's
; twist: a byte-2 that is a generic continuation (0x80-0xBF) but out of the lead's
; special range is consumed (1 FFFD, advance 2); a non-continuation byte-2 is not.
; Status: 0, 0x107 STATUS_SOME_NOT_MAPPED, or 0xC0000023 STATUS_BUFFER_TOO_SMALL.
;
; ------------------------------------------------------------------------------
; A NULL DESTINATION IS THE MEASURING MODE, ADDED 2026-09-16 -- IT WAS MISSING.
;
; RtlUTF8ToUnicodeN(NULL, 0, &produced, src, srcLen) is the documented way to ask
; this function how many bytes of UTF-16 the output will need: the shipped export
; returns STATUS_SUCCESS with `produced` set and writes nothing. This
; implementation returned STATUS_BUFFER_TOO_SMALL with produced = 0, and with a
; NULL pointer and a NON-ZERO size it dereferenced the pointer and faulted.
; discovery/utf8n_null_destination.c is the evidence; change 016 had the same gap
; and is corrected in the same way.
;
; WHY THE GATES DID NOT CATCH IT: this change is bit-exact against the live export
; over 400000 cases including every malformed class, and every one of them passes
; a real destination buffer. A NULL destination is not an edge of the LENGTH,
; which is what the corpora sweep -- it is a different MODE of the same function.
;
; THE COUNTING RULE IS THE ONE THIS DECODER ALREADY IMPLEMENTS, stated in the
; paragraph above and now also counted without converting: a stray continuation
; or an invalid lead is one unit and one byte; a lead whose byte-2 is not a
; continuation at all is one unit and one byte; a lead whose byte-2 IS a
; continuation but outside that lead's special range is one unit and TWO bytes;
; a truncated-but-valid prefix is one unit and however many bytes it had; and a
; complete four-byte sequence is TWO units. It was verified against the live
; measuring mode over 400000 random strings -- ASCII, continuation runs, lead
; runs, fully random bytes and valid UTF-8 -- with ZERO disagreements on the size
; AND on the status, before any of it was written in assembly.
; ------------------------------------------------------------------------------
;
; ISA: AVX2 + BMI1 + BMI2 (PDEP/POPCNT). Validated on Zen3.

.const
ALIGN 16
CQMASKw DW      8 dup(0C0E0h)                      ; per word: lead & 0xE0, continuation & 0xC0
CQWANTw DW      8 dup(080C0h)                      ; ... must be 0xC0 and 0x80
CQ1Ew   DW      16 dup(001Eh)                      ; the lead bits that separate C2..DF from C0/C1
CQDECw  DW      8 dup(3F1Fh)                       ; per word: lead & 0x1F, continuation & 0x3F
CQMULb  DB      8 dup(40h, 01h)                    ; VPMADDUBSW: lead*0x40 + continuation
; the three-byte block: one 3-byte sequence per 32-bit lane, the same pattern in both 128-bit lanes
CQ3SHUF DB      0,1,2,80h, 3,4,5,80h, 6,7,8,80h, 9,10,11,80h
        DB      0,1,2,80h, 3,4,5,80h, 6,7,8,80h, 9,10,11,80h
CQ3MSKd DD      8 dup(00C0C0F0h)                   ; lead & 0xF0, both continuations & 0xC0
CQ3WNTd DD      8 dup(008080E0h)                   ; ... must be 0xE0, 0x80, 0x80
CQ0Fd   DD      8 dup(0000000Fh)                   ; the lead's low nibble: 0 is E0, D is ED
CQ0Dd   DD      8 dup(0000000Dh)
CQ3Fd   DD      8 dup(0000003Fh)
; the four-byte block: a 4-byte sequence IS a 32-bit lane, so nothing has to be spread
CQ4MSKd DD      4 dup(0C0C0C0FCh)                  ; lead & 0xFC, all three continuations & 0xC0
CQ4WNTd DD      4 dup(808080F0h)                   ; ... must be 0xF0 and three 0x80s
CQ03d   DD      4 dup(00000003h)                   ; the lead's low two bits: 0 is F0
CQ30d   DD      4 dup(00003000h)                   ; byte 2's 0x30 bits: zero means 0x80..0x8F
CQ07d   DD      4 dup(00000007h)
CQ3FFd  DD      4 dup(000003FFh)
CQ10000d DD     4 dup(00010000h)
CQD800d DD      4 dup(0000D800h)
CQDC00d DD      4 dup(0000DC00h)
; the mixed block: one BYTE per 16-bit lane, so a lead and its continuation can be seen together
CQE0w   DW      16 dup(00E0h)
CQC0w   DW      16 dup(00C0h)
CQ80w   DW      16 dup(0080h)
CQ1Fw   DW      16 dup(001Fh)
CQ3Fw   DW      16 dup(003Fh)

; -------------------------------------------------------------------------------------------------
; THE COMPACTION TABLE for the mixed block, generated by the assembler rather than pasted in.
;
; Eight input positions produce between four and eight UTF-16 units, depending on how many of them
; are continuation bytes belonging to the position before. Each position's unit is computed in its
; own 16-bit lane and the lanes are then compacted by one VPSHUFB, so the only thing that varies is
; the shuffle -- 256 of them, one per combination of which positions are KEPT.
;
; A kept position contributes its two bytes; a continuation contributes nothing, because its
; character was already produced by the lead before it. correctness.c checks every entry against
; the same rule written in C.
; -------------------------------------------------------------------------------------------------
ALIGN 16
MIXTAB LABEL BYTE
PKI = 0
REPT 256
    PKN = 0
    PKJ = 0
    REPT 8
        IF (PKI SHR PKJ) AND 1
            DB (2*PKJ)
            DB (2*PKJ)+1
            PKN = PKN + 2
        ENDIF
        PKJ = PKJ + 1
    ENDM
    REPT 16 - PKN
        DB 80h
    ENDM
    PKI = PKI + 1
ENDM

PUBLIC wia_u82u_mix_table

; =================================================================================================
; THE WIDTH-AGNOSTIC DECODER (`gen64`) -- AVX512 VBMI + VBMI2, Tiger Lake only.
;
; WHY IT EXISTS. Every block above needs its bytes to be the SAME KIND of sequence. Real text is
; not: English prose with an accent and a euro sign is one-, two- and three-byte sequences
; interleaved, and Hindi or Thai is three-byte sequences whose lead 0xE0 the three-byte block
; deliberately declines. discovery/utf8_width_mixtures.c measured what that costs -- 0.29x to 0.45x
; against the shipped decoder on every mixed-width class, because the general case is SCALAR and
; mixed-width text is all general case. Change 290 (MultiByteToWideChar) is PARKED on the same
; defect, because it uses this file as its engine.
;
; THE SHAPE. One 64-byte load, and then the whole block is decoded without caring what widths are
; in it:
;
;   1. a byte is a CONTINUATION iff its signed value is below -64 -- one VPCMPB against 0xC0
;      classifies all 64. Everything else STARTS a character, so `leadmask` is that mask inverted.
;   2. a character ENDS at position e iff position e+1 starts one, so `endmask = leadmask >> 1`.
;      POPCNT of it is how many characters are COMPLETE inside the block.
;   3. VPCOMPRESSB of the identity by those two masks turns the masks into POSITIONS: p(j) for each
;      character's first byte, p(j+1) for the byte after its last. Their difference is its LENGTH,
;      in a byte lane, for every character at once -- and that is the step the AVX2 file cannot do.
;   4. VPERMB gathers each character into its own 32-bit lane RIGHT-ALIGNED -- last byte in byte 0,
;      lead in byte L-1 -- so ONE mask-and-shift expression decodes all four widths:
;          cp = (m & 7F) | ((m>>2) & 0FC0) | ((m>>4) & 3F000) | ((m>>6) & 1C0000)
;      with `m` the lane masked by a four-byte pattern chosen by L (VPERMB again, index 4*L+k).
;      Verified by hand for L=1,2,3,4 and then by the corpus.
;   5. VPCOMPRESSW writes the answer: one word per character, plus a second for each surrogate
;      pair, with a memory destination and a write mask so it stores EXACTLY the units produced.
;
; VALIDATION -- THE HARD HALF, AND THE PART THAT HAS TO BE EXACT.
; The block is decoded only if all of the following hold over the bytes it will consume:
;   (a) length == the length the lead asks for, for every character. One VPCMPB. This alone covers
;       a stranded continuation, a truncated sequence, and a lead whose continuations are missing.
;   (b) no 0xC0/0xC1 (overlong two-byte), no 0xF5..0xFF (never a lead), and the four leads with a
;       NARROW second byte are in range: E0 needs A0..BF, ED needs 80..9F, F0 needs 90..BF, F4
;       needs 80..8F. Those are the overlongs, the encoded surrogates and everything above
;       U+10FFFF -- exactly the cases ntdll substitutes rather than decodes.
;
;       ALL OF (b) IS ONE THREE-WAY AND of three nibble lookups, the way a UTF-8 VALIDATOR does it:
;       a table on the lead's low nibble, one on its high nibble, and one on the NEXT byte's high
;       nibble, with one bit per error class. The bit survives all three tables only for a byte
;       that really is one of those errors. Bits 4 and 5 are set in every entry of the third table,
;       so the C0/C1 and F5..FF tests -- which do not look at the next byte at all -- ride through
;       the same instruction.
; Anything else falls to the blocks below, and then to the scalar decoder, unchanged.
; =================================================================================================
WIAK64 SEGMENT ALIGN(64) READONLY 'CONST'
GC0     DB      64 dup(0C0h)                      ; signed < -64 is exactly 0x80..0xBF
GNIB    DB      64 dup(0Fh)
GID     LABEL   BYTE                              ; 0..63   -- the position of each byte
GI = 0
REPT 64
    DB  GI
    GI = GI + 1
ENDM
GID1    LABEL   BYTE                              ; 1..64   -- and the position after it
GI = 1
REPT 64
    DB  GI
    GI = GI + 1
ENDM
GREPA   LABEL   BYTE                              ; character j of 0..15 -> its four byte lanes
GJ = 0
REPT 16
    DB  GJ, GJ, GJ, GJ
    GJ = GJ + 1
ENDM
GSUB4   DB      16 dup(1,2,3,4)                   ; gather index = p(j+1) - 1 - k
GK4     DB      16 dup(0,1,2,3)
; the low nibble of a byte -- which error classes it COULD be
;   bit0/bit2 E0-or-F0 (low nibble 0) | bit1 ED | bit3 F4 | bit4 C0/C1 | bit5 F5..FF
GTLO    DB      15h,10h,00h,00h,08h,20h,20h,20h,20h,20h,20h,20h,20h,22h,20h,20h
        DB      48 dup(0)
; the high nibble -- which of those classes this byte is actually in
GTHI    DB      00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,10h,00h,03h,2Ch
        DB      48 dup(0)
; the NEXT byte's high nibble -- whether that second byte is out of the lead's narrow range.
; bits 4 and 5 are set everywhere so the C0/C1 and F5..FF verdicts pass through unchanged.
GTB2    DB      30h,30h,30h,30h,30h,30h,30h,30h,35h,39h,3Ah,3Ah,30h,30h,30h,30h
        DB      48 dup(0)
; the length a lead asks for, from its high nibble (8..B is a continuation and asks for none)
GEXP    DB      1,1,1,1,1,1,1,1,0,0,0,0,2,2,3,4
        DB      48 dup(0)
; the payload mask of a RIGHT-ALIGNED sequence, indexed by 4*L + k
GMTAB   DB      000h,000h,000h,000h               ; L=0 -- a lane past the end of the block
        DB      0FFh,000h,000h,000h               ; L=1  b0
        DB      0FFh,01Fh,000h,000h               ; L=2  b1 b0
        DB      0FFh,03Fh,00Fh,000h               ; L=3  b2 b1 b0
        DB      0FFh,03Fh,03Fh,007h               ; L=4  b3 b2 b1 b0
        DB      44 dup(0)
G7F     DD      16 dup(0000007Fh)
G0FC0   DD      16 dup(00000FC0h)
G3F000  DD      16 dup(0003F000h)
G1C0000 DD      16 dup(001C0000h)
GC2     DB      64 dup(0C2h)
GF5     DB      64 dup(0F5h)
GFFFDW  DW      32 dup(0FFFDh)
G16     DB      64 dup(16)
GE0     DB      64 dup(0E0h)
GF0     DB      64 dup(0F0h)
G30     DB      64 dup(30h)   ; the verdict bits that mean "this byte can never lead"
G0F     DB      64 dup(0Fh)   ; ... and the ones that mean "its second byte is out of range"
GFFFD   DD      16 dup(0000FFFDh)
GFFFF   DD      16 dup(0000FFFFh)
G10000  DD      16 dup(00010000h)
GD800   DD      16 dup(0000D800h)
G3FF    DD      16 dup(000003FFh)
GDC00   DD      16 dup(0000DC00h)
WIAK64 ENDS

; sixteen characters: gather, decode, split the surrogates, and store exactly what came out.
; RIDX says which sixteen (it starts at GREPA = 0..15 and steps by sixteen); r9d is how many
; of them are real.
GENHALF MACRO RIDX
        vpermb    zmm20, RIDX, zmm4                 ; p(j+1), replicated over four byte lanes
        vpsubb    zmm20, zmm20, zmmword ptr [GSUB4] ; the four gather indices of character j
        vpermb    zmm21, zmm20, zmm0                ; the sequence, right-aligned in its dword
        vpermb    zmm22, RIDX, zmm18                ; its length, replicated the same way
        vpaddb    zmm22, zmm22, zmm22
        vpaddb    zmm22, zmm22, zmm22               ; 4*L  (byte adds: nothing crosses a lane)
        vpaddb    zmm22, zmm22, zmmword ptr [GK4]   ; 4*L + k
        vpermb    zmm22, zmm22, zmmword ptr [GMTAB]
        vpandd    zmm21, zmm21, zmm22               ; only the payload bits of each byte survive
        vpsrld    zmm23, zmm21, 2
        vpsrld    zmm24, zmm21, 4
        vpsrld    zmm25, zmm21, 6
        vpandd    zmm21, zmm21, zmmword ptr [G7F]
        vpandd    zmm23, zmm23, zmmword ptr [G0FC0]
        vpandd    zmm24, zmm24, zmmword ptr [G3F000]
        vpandd    zmm25, zmm25, zmmword ptr [G1C0000]
        vpternlogd zmm21, zmm23, zmm24, 0FEh        ; A or B or C
        vpord     zmm21, zmm21, zmm25               ; the code point, all four widths at once
        vmovdqu32 zmm21{k7}, zmmword ptr [GFFFD]  ; ... unless the subpart was malformed
        vpcmpud   k5, zmm21, zmmword ptr [GFFFF], 6 ; above the BMP: it needs a surrogate pair
        vpsubd    zmm23, zmm21, zmmword ptr [G10000]
        vpsrld    zmm24, zmm23, 10
        vpaddd    zmm24, zmm24, zmmword ptr [GD800] ; the high surrogate
        vpandd    zmm23, zmm23, zmmword ptr [G3FF]
        vpaddd    zmm23, zmm23, zmmword ptr [GDC00]
        vpslld    zmm23, zmm23, 16                  ; the low surrogate, above it in the same lane
        vpord     zmm23, zmm23, zmm24
        vmovdqa32 zmm21{k5}, zmm23
        kmovw     eax, k5
        mov       ecx, r9d
        ; A LANE PAST THE LAST CHARACTER IS NOT SILENT. `p(j)` comes from the LEAD mask and `p(j+1)`
        ; from the END mask, and the lead mask has one more bit set than the end mask -- so the lane
        ; after the last complete character gets p(j+1)=0 and p(j)=the last lead, i.e. a NEGATIVE
        ; length, which lands on the four-byte entry of the width table and decodes four real bytes
        ; into a real surrogate pair. It was writing one extra unit per block. The even slots were
        ; already limited to the characters that exist; the odd ones have to be too.
        bzhi      eax, eax, ecx
        add       ecx, ecx
        mov       r11d, -1
        bzhi      r11d, r11d, ecx
        and       r11d, 55555555h                   ; one word for each real character ...
        mov       ecx, 0AAAAAAAAh
        pdep      edx, eax, ecx
        or        r11d, edx                         ; ... and a second one for each pair
        kmovd     k6, r11d
        popcnt    eax, eax
        add       eax, r9d                          ; the units this half produced
        vpcompressw zmmword ptr [rbx + r15*2]{k6}, zmm21
        add       r15, rax
ENDM

.code

; correctness.c calls this to check the assembler-generated table against the same rule in C
wia_u82u_mix_table PROC
        lea       rax, [MIXTAB]
        ret
wia_u82u_mix_table ENDP

wia_u82u PROC
        test      rcx, rcx
        jz        u82u_measure                      ; a NULL destination asks for the SIZE only
        push      rbx
        push      rsi
        push      rdi
        push      r12
        push      r13
        push      r14
        push      r15
        mov       rbx, rcx                          ; dst (wchar)
        shr       edx, 1
        mov       edi, edx                          ; maxWchars = maxBytes/2
        mov       r12, r8                           ; outLen ptr
        mov       rsi, r9                           ; src (utf8)
        mov       r13d, dword ptr [rsp + 60h]       ; srcBytes
        sub       rsp, 16
        mov       dword ptr [rsp], 0                ; notMapped
        mov       dword ptr [rsp+4], 0              ; overflow
        xor       r14, r14                          ; i (src index)
        xor       r15, r15                          ; o (dst wchar index)

mainloop:
        cmp       r14d, r13d
        jae       done
        ; ---- ASCII fast path: 16 bytes all < 0x80, room for 16 wchars ----
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        ascii8
        lea       eax, [r15 + 16]
        cmp       eax, edi
        ja        ascii8
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovmskb eax, xmm0
        test      eax, eax
        jnz       ascii8
        vpmovzxbw ymm0, xmm0
        vmovdqu   ymmword ptr [rbx + r15*2], ymm0
        add       r14, 16
        add       r15, 16
        jmp       mainloop
ascii8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 8
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        dispatch                          ; NOT scalar_win: if this hands the tight-room
                                                    ; case straight to the scalar path, every block
                                                    ; below inherits a room guarantee it never asked
                                                    ; for, and its own guard becomes a check that
                                                    ; cannot fail. Each block tests its own room.
        vmovq     xmm0, qword ptr [rsi + r14]
        vpmovmskb eax, xmm0
        and       eax, 0FFh
        jnz       dispatch
        vpmovzxbw xmm0, xmm0
        vmovdqu   xmmword ptr [rbx + r15*2], xmm0
        add       r14, 8
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; THE DISPATCH: ONE BYTE DECIDES WHICH BLOCK, instead of trying them in turn.
;
; There are four vector blocks below and they are mutually exclusive: a run of two-byte sequences is
; not a run of three-byte ones. Chained, the block that finally matches is reached only after every
; earlier one has loaded, tested and declined -- which cost `mixed` input, the last block in the
; chain, about eighteen wasted instructions per eight characters, a third of its total.
;
; The byte at the current position already says which block can possibly apply, because it is the
; LEAD of the next character. Five comparisons replace three failed probes, and a stray
; continuation or an overlong lead -- which no block decodes -- goes straight to the scalar path
; instead of being discovered three blocks later.
; -------------------------------------------------------------------------------------------------
dispatch:
        movzx     eax, byte ptr [rsi + r14]
        cmp       eax, 80h
        jb        gen64                             ; ASCII here, something else nearby
        cmp       eax, 0C2h
        jb        gen64s                            ; a stray continuation, or 0xC0 / 0xC1
        cmp       eax, 0E0h
        jb        two8
        cmp       eax, 0F0h
        jb        three8
        cmp       eax, 0F5h
        jb        four8
        jmp       gen64s                            ; 0xF5..0xFF is never a lead

; -------------------------------------------------------------------------------------------------
; THE TWO-BYTE BLOCK: SIXTEEN BYTES, EIGHT CHARACTERS, NO SHUFFLE.
;
; discovery/utf8_nonascii_rows.c measured this decoder at 0.36x to 0.60x on every class of input
; that is not ASCII, after e71db44 had already removed the vector re-entry that was costing it a
; second time over. What was left was a missing kernel: the ASCII blocks above handle the one case
; where every byte is one character, and everything else walked one character at a time.
;
; A run of two-byte sequences is the easiest of the remaining cases and the commonest in Latin-1
; supplement, Greek, Cyrillic, Hebrew and Arabic text: sixteen bytes are exactly eight characters,
; a fixed count, so there is nothing to compact and no table to index.
;
; THE VALIDITY TEST IS TWO COMPARISONS. Viewed as 16-bit words the input is [lead, continuation]
; per character, little-endian, so ANDing with 0xC0E0 and comparing against 0x80C0 says in one
; VPCMPEQW that every even byte is 0xC0..0xDF and every odd byte is 0x80..0xBF -- the whole
; structure of a two-byte run, tested in one instruction. The second comparison excludes 0xC0 and
; 0xC1, the overlong leads, which are the only bytes in 0xC0..0xDF whose low five bits are zero and
; which this decoder substitutes rather than decodes.
;
; AND THE ARITHMETIC IS ONE INSTRUCTION. VPMADDUBSW multiplies unsigned bytes by signed bytes and
; sums adjacent pairs, so masking with 0x3F1F and multiplying by [0x40, 0x01] IS
; (lead & 0x1F) * 64 + (continuation & 0x3F), which is the code point. The largest value it can
; produce is 0x7FF, so there is no saturation to think about.
; -------------------------------------------------------------------------------------------------
ALIGN 16
two8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpand     xmm1, xmm0, xmmword ptr [CQMASKw]
        vpcmpeqw  xmm1, xmm1, xmmword ptr [CQWANTw]
        vpmovmskb eax, xmm1
        cmp       eax, 0FFFFh
        jne       gen64                             ; not eight clean two-byte sequences
        vpand     xmm1, xmm0, xmmword ptr [CQ1Ew]
        vpxor     xmm2, xmm2, xmm2
        vpcmpeqw  xmm1, xmm1, xmm2
        vpmovmskb eax, xmm1
        test      eax, eax
        jnz       gen64                             ; a 0xC0 or 0xC1 lead: overlong, not decoded
        vpand     xmm1, xmm0, xmmword ptr [CQDECw]
        vpmaddubsw xmm1, xmm1, xmmword ptr [CQMULb]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 16
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; THE THREE-BYTE BLOCK: TWENTY-FOUR BYTES, EIGHT CHARACTERS.
;
; Three-byte sequences are every CJK character, every arrow, dash, quotation mark and currency sign
; above U+0800, and -- because this decoder substitutes U+FFFD, which is itself EF BF BD -- the
; output of every malformed run that has already been substituted once. They were 0.37x.
;
; Twenty-four bytes is eight sequences, a fixed count, so again there is nothing to compact. What
; three does that two did not is that it divides neither 16 nor 32, so the bytes have to be SPREAD
; before they can be worked on: one VPSHUFB puts each three-byte group into its own 32-bit lane,
; with the same pattern in both halves of the register. The two halves are loaded twelve bytes
; apart -- VPSHUFB cannot cross a 128-bit lane, so the second load starts where the first lane's
; four sequences end -- which is why this block reads 28 bytes to consume 24.
;
; After that the tests are single instructions again. ANDing a lane with 0x00C0C0F0 and comparing
; against 0x008080E0 says the lead is 0xE0..0xEF and both continuations are 0x80..0xBF. The lead's
; low nibble then excludes 0xE0 and 0xED, the two leads whose SECOND byte has a narrower range than
; 0x80..0xBF -- 0xE0 forbids the overlong forms and 0xED forbids the encoded surrogates, and this
; decoder substitutes both. Sending those two leads to the scalar path costs one sixteenth of the
; three-byte space and buys a validity test that is three instructions instead of a table.
; -------------------------------------------------------------------------------------------------
ALIGN 16
three8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 28                           ; 24 consumed, 28 read: see above
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vinserti128 ymm0, ymm0, xmmword ptr [rsi + r14 + 12], 1
        vpshufb   ymm0, ymm0, ymmword ptr [CQ3SHUF] ; one sequence per 32-bit lane
        vpand     ymm1, ymm0, ymmword ptr [CQ3MSKd]
        vpcmpeqd  ymm1, ymm1, ymmword ptr [CQ3WNTd]
        vpmovmskb eax, ymm1
        cmp       eax, -1
        jne       gen64                             ; not eight clean three-byte sequences
        vpand     ymm1, ymm0, ymmword ptr [CQ0Fd]
        vpxor     ymm2, ymm2, ymm2
        vpcmpeqd  ymm2, ymm1, ymm2                  ; lead 0xE0
        vpcmpeqd  ymm1, ymm1, ymmword ptr [CQ0Dd]   ; lead 0xED
        vpor      ymm1, ymm1, ymm2
        vpmovmskb eax, ymm1
        test      eax, eax
        jnz       gen64                             ; those two leads have narrower second bytes

        vpand     ymm1, ymm0, ymmword ptr [CQ0Fd]
        vpslld    ymm1, ymm1, 12                    ; the lead's four bits
        vpsrld    ymm2, ymm0, 8
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fd]
        vpslld    ymm2, ymm2, 6                     ; the first continuation
        vpor      ymm1, ymm1, ymm2
        vpsrld    ymm2, ymm0, 16
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fd]
        vpor      ymm1, ymm1, ymm2                  ; the second continuation
        vpackusdw ymm1, ymm1, ymm1
        vpermq    ymm1, ymm1, 8                     ; lane 0's four, then lane 1's four
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 24
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; THE FOUR-BYTE BLOCK: SIXTEEN BYTES, FOUR SEQUENCES, EIGHT UTF-16 UNITS.
;
; A four-byte sequence IS a 32-bit lane, so unlike the three-byte block nothing has to be spread:
; sixteen bytes are four sequences exactly, and four surrogate pairs are exactly sixteen bytes out.
; This is the emoji and supplementary-plane path, and it was 0.52x.
;
; The validity test is the same single comparison as the other blocks -- AND with 0xC0C0C0FC,
; compare against 0x808080F0 -- which says the lead is 0xF0..0xF3 and all three continuations are
; 0x80..0xBF. Excluding lead 0xF0 then takes one more test on its low two bits, and leaves this
; block covering U+40000..U+FFFFF. The two leads it does not take are the two with narrower second
; bytes: 0xF0 forbids the overlong forms below U+10000 and 0xF4 stops at U+10FFFF. Both go to the
; scalar path, which substitutes exactly what the shipped decoder substitutes.
;
; The surrogate split is the only part that is not shared with the other blocks, and it is four
; instructions: a code point above 0x10000 becomes 0xD800 + (v >> 10) and 0xDC00 + (v & 0x3FF),
; and the pair is assembled as ONE 32-bit lane -- high surrogate in the low half, low surrogate in
; the high half -- so that a plain store puts them in the right order.
; -------------------------------------------------------------------------------------------------
ALIGN 16
four8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpand     xmm1, xmm0, xmmword ptr [CQ4MSKd]
        vpcmpeqd  xmm1, xmm1, xmmword ptr [CQ4WNTd]
        vpmovmskb eax, xmm1
        cmp       eax, 0FFFFh
        jne       gen64                             ; not four clean four-byte sequences
        ; 0xF0 IS THE COMMONEST FOUR-BYTE LEAD, not a corner to skip: it carries U+10000 through
        ; U+3FFFF, which is every emoji there is. The first draft of this block excluded it to keep
        ; the test to one comparison, and the emoji rows did not move at all -- 0.53x before and
        ; 0.53x after, because the block was never entered. What 0xF0 actually needs is one extra
        ; condition on its SECOND byte: 0x80..0x8F would encode a value below U+10000, which is
        ; overlong, and every second byte in 0x80..0x8F is exactly the one with no 0x30 bits set.
        vpand     xmm1, xmm0, xmmword ptr [CQ03d]
        vpxor     xmm2, xmm2, xmm2
        vpcmpeqd  xmm1, xmm1, xmm2                  ; the lead is 0xF0
        vpand     xmm2, xmm0, xmmword ptr [CQ30d]   ; the mask sits where byte 2 already is
        vpxor     xmm3, xmm3, xmm3
        vpcmpeqd  xmm2, xmm2, xmm3                  ; ... and its second byte is 0x80..0x8F
        vpand     xmm1, xmm1, xmm2
        vpmovmskb eax, xmm1
        test      eax, eax
        jnz       gen64                             ; an overlong four-byte sequence

        vpand     xmm1, xmm0, xmmword ptr [CQ07d]
        vpslld    xmm1, xmm1, 18                    ; the lead's three bits
        vpsrld    xmm2, xmm0, 8
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpslld    xmm2, xmm2, 12
        vpor      xmm1, xmm1, xmm2
        vpsrld    xmm2, xmm0, 16
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpslld    xmm2, xmm2, 6
        vpor      xmm1, xmm1, xmm2
        vpsrld    xmm2, xmm0, 24
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpor      xmm1, xmm1, xmm2                  ; the code point
        vpsubd    xmm1, xmm1, xmmword ptr [CQ10000d]
        vpsrld    xmm2, xmm1, 10
        vpaddd    xmm2, xmm2, xmmword ptr [CQD800d] ; the high surrogate
        vpand     xmm1, xmm1, xmmword ptr [CQ3FFd]
        vpaddd    xmm1, xmm1, xmmword ptr [CQDC00d]
        vpslld    xmm1, xmm1, 16                    ; the low surrogate, above it
        vpor      xmm1, xmm1, xmm2
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 16
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; THE MIXED BLOCK: ASCII AND TWO-BYTE SEQUENCES TOGETHER, EIGHT POSITIONS AT A TIME.
;
; Every block above needs its eight or twenty-four bytes to be the SAME KIND of sequence, and that
; is the one thing real text never is. `mixed` -- ASCII alternating with two-byte letters, which is
; what Greek, Cyrillic, Hebrew, Arabic or accented Latin prose looks like once it has spaces and
; punctuation in it -- went through every one of those blocks, failed all of them, and walked one
; character at a time: 0.42x, the last class short of the shipped decoder and the commonest
; non-ASCII input there is.
;
; This block does not need the positions to agree. One BYTE per 16-bit lane, and a second copy of
; the same bytes shifted down by one, so each lane can see both a byte and the byte after it. Then:
;
;   * anything at 0xE0 or above ends the block -- three- and four-byte sequences have their own;
;   * 0xC0 and 0xC1 end it, because this decoder substitutes the overlong forms rather than
;     decoding them;
;   * the STRUCTURE is one comparison of two eight-bit masks: the set of positions holding a lead
;     must equal the set of positions whose NEXT byte is a continuation. That single CMP says every
;     lead is followed by its continuation AND that no continuation is stranded -- and one more bit
;     test says position 0 is not itself a continuation, which would belong to a character that
;     ended before this block began.
;
; What is left is a lane per position holding either the ASCII character or the decoded two-byte
; value, and a VPSHUFB indexed by the eight-bit mask of positions that are NOT continuations
; compacts them. POPCNT of that same mask is how many units came out; a lead in the LAST position
; means its continuation was the ninth byte, so nine were consumed rather than eight.
; -------------------------------------------------------------------------------------------------
; -------------------------------------------------------------------------------------------------
; THE MIXED BLOCK, SIXTEEN POSITIONS AT A TIME.
;
; The eight-position version below is the same idea and took `mixed` from 0.42x to 0.84x; with the
; dispatch above removing the failed probes it reached 0.98x, which is a tie and is not a margin
; worth publishing. What is left is setup: classifying eight positions costs about as much as
; classifying sixteen, and eight positions of alternating ASCII and two-byte text yield only six
; UTF-16 units, so more than half the work was overhead.
;
; Sixteen positions are classified in one 256-bit pass and then compacted as TWO halves, because the
; compaction table is indexed by eight bits and VPSHUFB cannot cross a 128-bit lane anyway. PEXT
; turns each VPMOVMSKB result -- two identical bits per 16-bit lane -- into the one-bit-per-position
; mask the tests and the table want.
;
; Everything else is exactly the eight-position rule: nothing at 0xE0 or above, no 0xC0 or 0xC1, the
; set of positions holding a lead equals the set whose next byte is a continuation, and position 0
; is not itself a continuation. Seventeen bytes are read to consume at most seventeen.
; -------------------------------------------------------------------------------------------------
; -------------------------------------------------------------------------------------------------
; gen64 -- the width-agnostic block. See the long note above the constants.
;
; It needs 64 source bytes (the load is exactly 64, so the guard is the page guard) and room for 64
; UTF-16 units, which is the most 32 characters can produce. Below either of those it declines to
; the sixteen-position mixed block, which is unchanged.
; -------------------------------------------------------------------------------------------------
; TWO ENTRIES, AND THE DIFFERENCE IS WHICH FALLBACK IS LEGAL.
;
; `gen64` is entered from the dispatch and from a homogeneous block that declined, so the byte at
; the cursor is a real lead, and if this block cannot run the sixteen-position mixed block may.
;
; `gen64s` is entered when the byte at the cursor is NOT a lead -- a stray continuation, 0xC0/0xC1,
; or 0xF5..0xFF. gen64 handles those; `mix16` and `mix8` DO NOT. Both of them deliberately dropped
; the test that position 0 is a character start, because the dispatch used to guarantee it, and the
; comment in mix16 says so. Sending a stray continuation down the old fallback made them skip it
; silently: the fuzz corpus produced `... 004F FFFD 0713 ...` from ntdll and `... 004F 0713 ...`
; from here, one U+FFFD short. So this entry falls back to the SCALAR walk, never to those blocks.
ALIGN 16
gen64s:
        mov       eax, edi
        sub       eax, r15d
        cmp       eax, 2
        jb        scalar_win                        ; one subpart can still be a surrogate PAIR
        jmp       gen64_load
ALIGN 16
gen64:
        mov       eax, edi
        sub       eax, r15d
        cmp       eax, 2
        jb        mix16
gen64_load:
        ; -----------------------------------------------------------------------------------------
        ; THE LOAD IS MASKED, WHICH IS BOTH THE PAGE GUARD AND THE END-OF-BUFFER RULE.
        ;
        ; An AVX-512 masked load does not fault on a masked-off element, so reading 64 bytes with
        ; only the bytes that exist enabled cannot touch the next page. There is therefore no
        ; "64 bytes must remain" guard and no tail handed to a slower block. The first draft did
        ; have that guard, and the 64-byte row of ASCII-with-a-bad-byte came in at 0.40x, because a
        ; 64-byte buffer never has 64 bytes LEFT once the ASCII block has eaten the front of it.
        ;
        ; The bytes past the end read as ZERO, and that is not a hazard -- it is the truncation rule
        ; for free. 0x00 is never a continuation, so it ends a sequence that would have run past the
        ; buffer at exactly the byte the shipped decoder ends it at: `E2 82` as the last two bytes
        ; is one U+FFFD and two bytes consumed, on both sides. All that is left to do is to not
        ; COUNT the padding, which is what the two masks below are for.
        ; -----------------------------------------------------------------------------------------
        mov       r11d, r13d
        sub       r11d, r14d                        ; the bytes that really exist
        mov       rdx, -1
        cmp       r11d, 64
        jae       gen64_wide
        bzhi      rdx, rdx, r11
gen64_wide:
        kmovq     k1, rdx
        kmovq     k0, rdx                           ; kept here: every GPR below is spoken for
        vmovdqu8  zmm0{k1}{z}, zmmword ptr [rsi + r14]

        ; -----------------------------------------------------------------------------------------
        ; ASCII WITH RUBBISH IN IT -- the shape that log files, network buffers and user input
        ; actually have, and the one the general path is worst at.
        ;
        ; If NO byte in the block is 0xC2..0xF4 then no byte can lead a multi-byte sequence, so every
        ; one of the 64 is its own subpart: a byte below 0x80 is itself, and every other byte -- a
        ; stray continuation, 0xC0/0xC1, 0xF5..0xFF -- is one U+FFFD and one byte, which is exactly
        ; what the shipped decoder does with it. Sixty-four bytes become sixty-four units with two
        ; widenings and a masked load, and none of the position arithmetic below is needed.
        ;
        ; WHY IT EARNS ITS PLACE. Without it the general path swallowed the whole buffer on this
        ; input -- discovery/utf8_width_mixtures.c's "one bad byte every 32/64" rows -- at about ten
        ; times the cost per byte of the ASCII block, because one stray byte in sixty-four is enough
        ; to keep the ASCII block out. The two comparisons that decline it cost four instructions on
        ; every other kind of block.
        ; -----------------------------------------------------------------------------------------
        vpcmpub   k1, zmm0, zmmword ptr [GC2], 5
        vpcmpub   k2, zmm0, zmmword ptr [GF5], 1
        kandq     k1, k1, k2
        kortestq  k1, k1
        jnz       gen64_full                        ; something in here really does lead a sequence
        mov       eax, edi
        sub       eax, r15d
        cmp       eax, r11d
        jb        gen64_full                        ; this many bytes is exactly this many units
        vpmovb2m  k1, zmm0                          ; top bit set = not ASCII = one U+FFFD.
        kmovq     rax, k1                           ; the padding reads 0x00, so it is never set
        vpmovzxbw zmm1, ymm0
        vextracti64x4 ymm2, zmm0, 1
        vpmovzxbw zmm2, ymm2
        kmovd     k2, eax
        mov       rcx, rax
        shr       rcx, 32
        kmovd     k3, ecx
        vmovdqu16 zmm1{k2}, zmmword ptr [GFFFDW]
        vmovdqu16 zmm2{k3}, zmmword ptr [GFFFDW]
        kmovd     k4, edx                           ; rdx is still `rm`: the store is masked to the
        mov       rcx, rdx                          ; bytes that exist, so a short block cannot put
        shr       rcx, 32                           ; its own padding into the caller's buffer
        kmovd     k5, ecx
        vmovdqu16 zmmword ptr [rbx + r15*2]{k4}, zmm1
        vmovdqu16 zmmword ptr [rbx + r15*2 + 64]{k5}, zmm2
        test      rax, rax
        setnz     al
        movzx     eax, al
        or        dword ptr [rsp], eax
        add       r15, r11
        add       r14, r11
        jmp       mainloop

gen64_full:
        ; ---- the verdict byte: every malformed class, for all 64 bytes, in three lookups ----
        vpandq    zmm1, zmm0, zmmword ptr [GNIB]
        vpsrlw    zmm2, zmm0, 4
        vpandq    zmm2, zmm2, zmmword ptr [GNIB]
        vmovdqu8  zmm17, zmmword ptr [GID1]
        vpermb    zmm3, zmm1, zmmword ptr [GTLO]
        vpermb    zmm5, zmm2, zmmword ptr [GTHI]
        vpermb    zmm19, zmm17, zmm2                ; the high nibble of the byte AFTER this one
        vpermb    zmm19, zmm19, zmmword ptr [GTB2]
        vpternlogd zmm3, zmm5, zmm19, 80h
        vpermb    zmm1, zmm2, zmmword ptr [GEXP]    ; the length each byte asks for

        ; ---- the six masks the maximal-subpart rule is built from ----
        vpcmpb    k1, zmm0, zmmword ptr [GC0], 1    ; signed < -64: a continuation byte
        vpcmpub   k2, zmm0, zmmword ptr [GC0], 5    ; >= 0xC0: takes a second byte
        vpcmpub   k3, zmm0, zmmword ptr [GE0], 5    ; >= 0xE0: a third
        vpcmpub   k4, zmm0, zmmword ptr [GF0], 5    ; >= 0xF0: a fourth
        vptestmb  k5, zmm3, zmmword ptr [G30]       ; 0xC0, 0xC1, 0xF5..0xFF -- never a lead
        vptestmb  k6, zmm3, zmmword ptr [G0F]       ; E0/ED/F0/F4 with a second byte out of range
        kmovq     rax, k1
        kmovq     r9,  k2
        kmovq     r10, k3
        kmovq     r11, k4
        kmovq     rcx, k5
        kmovq     rdx, k6

        ; ---- WHICH BYTES ARE SWALLOWED BY THE SEQUENCE IN FRONT OF THEM ----
        ; A byte belongs to the character before it only if it is a continuation AND some lead
        ; close enough behind it really reaches it. In mask arithmetic, for byte i:
        ;   the lead at i-1 takes a second byte, or
        ;   the lead at i-2 takes a third AND i-1 was a continuation AND its second byte was in
        ;     range (an out-of-range second byte ENDS the subpart at two bytes -- ntdll's twist), or
        ;   the lead at i-3 takes a fourth AND i-1 and i-2 were continuations AND likewise.
        ; An invalid lead reaches nothing, which is what makes 0xC0/0xF5 one byte and one U+FFFD.
        ; Everything NOT swallowed starts a maximal subpart -- valid or not -- and that is the
        ; boundary set the shipped decoder uses. It is the whole malformed rule, in twenty
        ; instructions, with no branch and no character-at-a-time walk.
        andn      r9, rcx, r9                       ; a lead that can take a second byte
        andn      r10, rcx, r10                     ; ... a third
        andn      r11, rcx, r11                     ; ... a fourth
        mov       rcx, rax
        shl       rcx, 1                            ; a continuation one byte back
        shl       r9, 1
        shl       r10, 2
        shl       r11, 3
        and       r10, rcx
        and       r11, rcx
        shl       rcx, 1                            ; ... and two bytes back
        and       r11, rcx
        mov       rcx, rdx
        shl       rcx, 2
        andn      r10, rcx, r10                     ; the out-of-range second byte stops it here
        shl       rdx, 3
        andn      r11, rdx, r11
        or        r9, r10
        or        r9, r11
        and       rax, r9                           ; swallowed
        not       rax                               ; S: every byte that STARTS a subpart
        ; ... and now drop the padding. A subpart ENDS at e when the next byte starts one, so the
        ; END mask is S>>1 confined to the bytes that exist -- which, in a SHORT block, picks up the
        ; last real subpart precisely because the first pad byte is a zero and therefore a start.
        ; The START mask keeps one extra bit, at that pad byte, so that "the m'th start" is still
        ; defined when m is every subpart there is. That lane is never decoded.
        kmovq     rdx, k0                           ; the bytes that exist
        mov       r9, rdx
        shl       r9, 1
        or        r9, 1
        and       r9, rax                           ; the starts, plus the first pad byte
        kmovq     k2, r9
        mov       r11, rax
        shr       r11, 1
        and       r11, rdx
        kmovq     k3, r11
        popcnt    r8, r11                           ; how many subparts are complete
        ; THE WHOLE BLOCK, NOT A FIXED SLICE OF IT. Consecutive blocks are serialised through the
        ; source cursor and the output cursor, so the cost of one is its DEPENDENCE CHAIN -- about
        ; the same whether it decodes sixteen subparts or sixty. Capping it at 32 halved the rate on
        ; ASCII-dominated input for nothing. The only real ceiling is the destination: m subparts
        ; can be 2*m units, so m is clamped by half the room that is left, and never by a constant.
        mov       eax, edi                          ; rax is free now; r9 carries the start mask
        sub       eax, r15d
        shr       eax, 1
        cmp       r8d, eax
        cmova     r8d, eax                          ; m subparts can be 2*m units
        test      r8d, r8d
        jz        gen_none                          ; no room for even one -- let the scalar rule
        mov       rcx, r8                           ; produce the partial write and the status
        mov       r11, 1
        shl       r11, cl
        pdep      r11, r11, r9                      ; isolate the m'th subpart start ...
        tzcnt     r10, r11                          ; ... which is what this block consumes

        ; ---- lengths, and which subparts are well formed ----
        vmovdqu8  zmm16, zmmword ptr [GID]
        vpcompressb zmm4{k3}{z}, zmm17              ; p(j+1)
        vpcompressb zmm5{k2}{z}, zmm16              ; p(j)
        vpcompressb zmm19{k2}{z}, zmm1              ; the length its first byte asks for
        vpsubb    zmm18, zmm4, zmm5                 ; the length it has
        vpcmpb    k7, zmm18, zmm19, 4               ; they disagree: substitute one U+FFFD
        ; ONE TEST DECIDES EVERY MALFORMED CLASS, because the boundary rule above already placed
        ; the end of the subpart: a truncated sequence is short, an invalid lead is one byte
        ; against an expected two or four, a stray continuation is one byte against an expected
        ; ZERO, and an out-of-range second byte is two bytes against an expected three or four.

        mov       r11, -1
        bzhi      r11, r11, r8
        kmovq     k6, r11
        kandq     k6, k6, k7
        kortestq  k6, k6
        setnz     al
        movzx     eax, al
        or        dword ptr [rsp], eax              ; STATUS_SOME_NOT_MAPPED

        ; ---- decode, sixteen subparts at a time, until the block is spent ----
        vmovdqu8  zmm27, zmmword ptr [GREPA]
gen_pass:
        mov       r9d, r8d
        cmp       r9d, 16
        jbe       gen_last
        mov       r9d, 16
gen_last:
        GENHALF   zmm27
        sub       r8d, r9d
        jz        gen_done
        kshiftrq  k7, k7, 16                        ; the next sixteen verdicts ...
        vpaddb    zmm27, zmm27, zmmword ptr [G16]   ; ... and the next sixteen subparts
        jmp       gen_pass
gen_done:
        add       r14, r10
        jmp       mainloop
gen_none:
        jmp       mix16
ALIGN 16
mix16:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 32
        jb        mix8
        lea       eax, [r15 + 16]
        cmp       eax, edi
        ja        mix8
        mov       r11d, 55555555h                   ; PEXT: one bit per 16-bit lane
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovzxbw ymm1, xmm0                        ; the bytes at 0..15
        vmovdqu   xmm2, xmmword ptr [rsi + r14 + 1]
        vpmovzxbw ymm2, xmm2                        ; the bytes at 1..16

        vpand     ymm3, ymm1, ymmword ptr [CQE0w]
        vpcmpeqw  ymm4, ymm3, ymmword ptr [CQC0w]   ; a lead, 0xC0..0xDF
        vpcmpeqw  ymm3, ymm3, ymmword ptr [CQE0w]   ; 0xE0 or above
        vpmovmskb eax, ymm3
        test      eax, eax
        jnz       mix8

        vpand     ymm3, ymm1, ymmword ptr [CQ1Ew]
        vpxor     ymm5, ymm5, ymm5
        vpcmpeqw  ymm3, ymm3, ymm5
        vpand     ymm3, ymm3, ymm4                  ; a lead whose low bits are zero: 0xC0 or 0xC1
        vpmovmskb eax, ymm3
        test      eax, eax
        jnz       mix8

        vpand     ymm3, ymm1, ymmword ptr [CQC0w]
        vpcmpeqw  ymm3, ymm3, ymmword ptr [CQ80w]   ; a continuation, at 0..15
        vpand     ymm5, ymm2, ymmword ptr [CQC0w]
        vpcmpeqw  ymm5, ymm5, ymmword ptr [CQ80w]   ; a continuation, at 1..16
        vpmovmskb eax, ymm5
        pext      r8d, eax, r11d
        vpmovmskb eax, ymm4
        pext      edx, eax, r11d
        cmp       r8d, edx
        jne       mix8                              ; a lead without its continuation, or the reverse
        vpmovmskb eax, ymm3
        pext      ecx, eax, r11d
        ; THE FIRST POSITION IS A CHARACTER START, and the dispatch above is the one place that
        ; says so: it sends every byte below 0xC2 that is not ASCII straight to the scalar path.
        ; An earlier draft tested it again here and in the eight-position block below, which looked
        ; careful and was not -- the test could never fail, so the mutation that BREAKS the
        ; dispatch was caught by nothing and reported as harmless. One live check beats two dead
        ; ones.

        vpand     ymm5, ymm1, ymmword ptr [CQ1Fw]
        vpsllw    ymm5, ymm5, 6
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fw]
        vpor      ymm5, ymm5, ymm2                  ; the two-byte value
        vpblendvb ymm1, ymm1, ymm5, ymm4            ; a lead's lane takes it; ASCII keeps itself

        not       ecx                               ; the positions that are NOT continuations
        lea       r10, [MIXTAB]
        mov       r9d, ecx
        and       r9d, 0FFh
        popcnt    eax, r9d
        shl       r9d, 4
        vpshufb   xmm3, xmm1, xmmword ptr [r10 + r9]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm3
        add       r15, rax
        vextracti128 xmm3, ymm1, 1
        shr       ecx, 8
        and       ecx, 0FFh
        popcnt    eax, ecx
        shl       ecx, 4
        vpshufb   xmm3, xmm3, xmmword ptr [r10 + rcx]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm3
        add       r15, rax
        shr       edx, 15                           ; a lead in the last position took a 17th byte
        and       edx, 1
        add       r14, 16
        add       r14, rdx
        jmp       mainloop

ALIGN 16
mix8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16                           ; at most 9 consumed; 16 read in one go
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovzxbw xmm1, xmm0                        ; the bytes at 0..7
        vpsrldq   xmm2, xmm0, 1
        vpmovzxbw xmm2, xmm2                        ; the bytes at 1..8

        vpand     xmm3, xmm1, xmmword ptr [CQE0w]
        vpcmpeqw  xmm4, xmm3, xmmword ptr [CQC0w]   ; a lead, 0xC0..0xDF
        vpcmpeqw  xmm3, xmm3, xmmword ptr [CQE0w]   ; 0xE0 or above
        vpmovmskb eax, xmm3
        test      eax, eax
        jnz       scalar_win

        vpand     xmm3, xmm1, xmmword ptr [CQ1Ew]
        vpxor     xmm5, xmm5, xmm5
        vpcmpeqw  xmm3, xmm3, xmm5
        vpand     xmm3, xmm3, xmm4                  ; a lead whose low bits are zero: 0xC0 or 0xC1
        vpmovmskb eax, xmm3
        test      eax, eax
        jnz       scalar_win

        vpand     xmm3, xmm1, xmmword ptr [CQC0w]
        vpcmpeqw  xmm3, xmm3, xmmword ptr [CQ80w]   ; a continuation, at 0..7
        vpand     xmm5, xmm2, xmmword ptr [CQC0w]
        vpcmpeqw  xmm5, xmm5, xmmword ptr [CQ80w]   ; a continuation, at 1..8
        vpacksswb xmm5, xmm5, xmm5
        vpmovmskb r8d, xmm5
        and       r8d, 0FFh
        vpacksswb xmm5, xmm4, xmm4
        vpmovmskb edx, xmm5
        and       edx, 0FFh
        cmp       r8d, edx
        jne       scalar_win                        ; a lead without its continuation, or the reverse
        vpacksswb xmm5, xmm3, xmm3
        vpmovmskb ecx, xmm5
        ; the first position is a character start; see the note in the 16-position block above

        vpand     xmm5, xmm1, xmmword ptr [CQ1Fw]
        vpsllw    xmm5, xmm5, 6
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fw]
        vpor      xmm5, xmm5, xmm2                  ; the two-byte value
        vpblendvb xmm1, xmm1, xmm5, xmm4            ; a lead's lane takes it; ASCII keeps itself

        not       ecx
        and       ecx, 0FFh                         ; the positions that are NOT continuations
        popcnt    eax, ecx
        lea       r10, [MIXTAB]
        shl       ecx, 4
        vpshufb   xmm1, xmm1, xmmword ptr [r10 + rcx]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r15, rax
        shr       edx, 7                            ; a lead in the last position took a ninth byte
        and       edx, 1
        add       r14, 8
        add       r14, rdx
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; THE SCALAR WINDOW, ADDED 2026-09-16. Before it, every scalar character jumped back to `mainloop`
; and paid for BOTH vector blocks again -- two loads, two VPMOVMSKBs and four comparisons -- to
; discover once more that the byte in front of it is not ASCII. On a string that is entirely
; two-byte sequences that cost was paid on every character for the whole string, and on input that
; alternates ASCII with non-ASCII it was paid twice per character. discovery/utf8_nonascii_rows.c
; measured what it came to: 0.33x to 0.48x against the shipped decoder on every class of input that
; is not ASCII, in a change published at 3.61x on input that is.
;
; This is change 263's rule, which this repository already wrote down and this file already broke:
; A SCALAR WALK MUST NOT RE-ENTER A VECTOR LOOP. The window is the cheapest possible statement of
; it -- once the blocks have failed, 32 source bytes are decoded one character at a time before
; they are tried again, so the probe is amortised over a whole cache line of input instead of over
; one character. The two comparisons in `scalar_next` replace two vector loads.
; -------------------------------------------------------------------------------------------------
scalar_win:
        lea       eax, [r14 + 32]
        mov       dword ptr [rsp + 8], eax          ; decode this far before probing again

scalar:
        movzx     r8d, byte ptr [rsi + r14]         ; L
        cmp       r8d, 80h
        jb        sc_ascii
        cmp       r8d, 0C2h
        jb        sc_fffd1
        cmp       r8d, 0F5h
        jae       sc_fffd1
        ; expected length
        mov       r11d, 2
        cmp       r8d, 0E0h
        jb        have_exp
        mov       r11d, 3
        cmp       r8d, 0F0h
        jb        have_exp
        mov       r11d, 4
have_exp:
        ; byte-2 special range lo/hi
        mov       r9d, 80h
        mov       r10d, 0BFh
        cmp       r8d, 0E0h
        jne       chk_ED
        mov       r9d, 0A0h
        jmp       have_range
chk_ED:
        cmp       r8d, 0EDh
        jne       chk_F0
        mov       r10d, 9Fh
        jmp       have_range
chk_F0:
        cmp       r8d, 0F0h
        jne       chk_F4
        mov       r9d, 90h
        jmp       have_range
chk_F4:
        cmp       r8d, 0F4h
        jne       have_range
        mov       r10d, 8Fh
have_range:
        mov       ecx, 1                            ; consumed
        mov       edx, 1                            ; j
cons_loop:
        cmp       edx, r11d
        jae       cons_valid
        lea       eax, [r14 + rdx]
        cmp       eax, r13d
        jae       cons_invalid                      ; truncated
        movzx     eax, byte ptr [rsi + rax]         ; b
        cmp       eax, 80h
        jb        cons_invalid
        cmp       eax, 0BFh
        ja        cons_invalid
        inc       ecx
        cmp       edx, 1
        jne       cons_next
        cmp       eax, r9d
        jb        cons_invalid
        cmp       eax, r10d
        ja        cons_invalid
cons_next:
        inc       edx
        jmp       cons_loop

cons_invalid:
        mov       dword ptr [rsp], 1                ; notMapped
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], 0FFFDh
        inc       r15
        add       r14, rcx
        jmp       scalar_next

cons_valid:
        cmp       r11d, 2
        je        dec2
        cmp       r11d, 3
        je        dec3
        ; ---- 4-byte -> surrogate pair ----
        and       r8d, 7
        shl       r8d, 18
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        shl       eax, 12
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 2]
        and       eax, 3Fh
        shl       eax, 6
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 3]
        and       eax, 3Fh
        or        r8d, eax                          ; cp
        cmp       r15d, edi
        jae       ov_stop                           ; no room for high surrogate
        sub       r8d, 10000h
        mov       eax, r8d
        shr       eax, 10
        add       eax, 0D800h
        mov       word ptr [rbx + r15*2], ax        ; high surrogate
        inc       r15
        cmp       r15d, edi
        jae       ov_stop                           ; room for high only -> overflow
        mov       eax, r8d
        and       eax, 3FFh
        add       eax, 0DC00h
        mov       word ptr [rbx + r15*2], ax        ; low surrogate
        inc       r15
        add       r14, 4
        jmp       scalar_next
dec2:
        and       r8d, 1Fh
        shl       r8d, 6
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        or        r8d, eax
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], r8w
        inc       r15
        add       r14, 2
        jmp       scalar_next
dec3:
        and       r8d, 0Fh
        shl       r8d, 12
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        shl       eax, 6
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 2]
        and       eax, 3Fh
        or        r8d, eax
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], r8w
        inc       r15
        add       r14, 3
        jmp       scalar_next

sc_ascii:
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        movzx     eax, byte ptr [rsi + r14]
        mov       word ptr [rbx + r15*2], ax
        inc       r15
        inc       r14
        jmp       scalar_next
sc_fffd1:
        mov       dword ptr [rsp], 1
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], 0FFFDh
        inc       r15
        inc       r14
        jmp       scalar_next
scalar_next:
        cmp       r14d, r13d
        jae       done                              ; the source is finished
        cmp       r14d, dword ptr [rsp + 8]
        jb        scalar                            ; still inside the window: stay scalar
        jmp       mainloop                          ; the window is spent: probe the blocks again

ov_stop:
        mov       dword ptr [rsp+4], 1

done:
        lea       eax, [r15*2]
        mov       dword ptr [r12], eax              ; *outLen = wchars*2
        mov       eax, dword ptr [rsp+4]
        test      eax, eax
        jnz       ret_small
        mov       eax, dword ptr [rsp]
        test      eax, eax
        jnz       ret_nm
        xor       eax, eax
        jmp       epi
ret_small:
        mov       eax, 0C0000023h
        jmp       epi
ret_nm:
        mov       eax, 107h
epi:
        add       rsp, 16
        vzeroupper
        pop       r15
        pop       r14
        pop       r13
        pop       r12
        pop       rdi
        pop       rsi
        pop       rbx
        ret
; ---------------------------------------------------------------------------------------------
; THE MEASURING MODE. Entered before the prologue, so it is a leaf: only the volatile registers
; and the caller's shadow space, which holds the two things there is no register left for.
;
;   r9 = src,  [rsp+40] = srcBytes,  [rsp+8] = notMapped,  [rsp+16] = the outLen pointer
;
; One byte at a time: this path is not the performance case, the conversion is.
; ---------------------------------------------------------------------------------------------
u82u_measure:
        mov       qword ptr [rsp + 16], r8          ; the outLen pointer, so r8 can be scratch
        mov       dword ptr [rsp + 8], 0            ; notMapped
        mov       r10d, dword ptr [rsp + 40]        ; srcBytes
        xor       r11d, r11d                        ; index
        xor       eax, eax                          ; units produced
        jmp       w_test

; THE ASCII BLOCK, ADDED 2026-09-16 BECAUSE A CALLER MEASURED IT. The first version of this mode
; walked one byte at a time, which is the right shape for a path nothing calls in a loop -- and
; then change 268 called it on every allocating conversion and on every conversion into a tight
; destination, where the shipped code's own sizing pass is vectorised. On 4000 ASCII bytes that
; scalar walk cost more than the conversion it was sizing. Thirty-two bytes are tested at once
; here: VPMOVMSKB collects their top bits, and if none is set then all thirty-two are one UTF-16
; unit each and the count moves by 32 with no per-byte work. It needs no constant and no compare --
; the mask IS the answer. Anything else falls into the byte-at-a-time rule below, which is
; unchanged and still decides every multi-byte and every malformed case.
ALIGN 16
w_fast: vmovdqu   ymm0, ymmword ptr [r9 + r11]
        vpmovmskb ecx, ymm0
        test      ecx, ecx
        jnz       w_loop                            ; a byte with its top bit set: go carefully
        add       eax, 32
        add       r11, 32
        jmp       w_test
ALIGN 16
w_loop:
        movzx     ecx, byte ptr [r9 + r11]
        cmp       ecx, 80h
        jb        w_ascii
        cmp       ecx, 0C2h
        jb        w_bad1                            ; a stray continuation, or C0/C1
        cmp       ecx, 0E0h
        jb        w_two
        cmp       ecx, 0F0h
        jb        w_three
        cmp       ecx, 0F5h
        jb        w_four
        jmp       w_bad1                            ; F5..FF is never a lead

w_ascii:inc       eax
        inc       r11
        jmp       w_test
w_bad1: mov       dword ptr [rsp + 8], 1
        inc       eax
        inc       r11
        jmp       w_test
w_bad2: mov       dword ptr [rsp + 8], 1
        inc       eax
        add       r11, 2
        jmp       w_test
w_bad3: mov       dword ptr [rsp + 8], 1
        inc       eax
        add       r11, 3
        jmp       w_test

w_two:  lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1                            ; nothing follows the lead
        movzx     r8d, byte ptr [r9 + r11 + 1]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1                            ; what follows is not a continuation
        inc       eax
        add       r11, 2
        jmp       w_test

w_three:lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1
        movzx     edx, byte ptr [r9 + r11 + 1]
        mov       r8d, edx
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1                            ; not a continuation: consume ONE
        mov       r8d, 80h                          ; the lead's own lower bound
        cmp       ecx, 0E0h
        jne       w3lo
        mov       r8d, 0A0h
w3lo:   cmp       edx, r8d
        jb        w_bad2                            ; a continuation, but out of range: consume TWO
        mov       r8d, 0BFh
        cmp       ecx, 0EDh
        jne       w3hi
        mov       r8d, 9Fh
w3hi:   cmp       edx, r8d
        ja        w_bad2
        lea       r8, [r11 + 2]
        cmp       r8, r10
        jae       w_bad2
        movzx     r8d, byte ptr [r9 + r11 + 2]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad2
        inc       eax
        add       r11, 3
        jmp       w_test

w_four: lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1
        movzx     edx, byte ptr [r9 + r11 + 1]
        mov       r8d, edx
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1
        mov       r8d, 80h
        cmp       ecx, 0F0h
        jne       w4lo
        mov       r8d, 90h
w4lo:   cmp       edx, r8d
        jb        w_bad2
        mov       r8d, 0BFh
        cmp       ecx, 0F4h
        jne       w4hi
        mov       r8d, 8Fh
w4hi:   cmp       edx, r8d
        ja        w_bad2
        lea       r8, [r11 + 2]
        cmp       r8, r10
        jae       w_bad2
        movzx     r8d, byte ptr [r9 + r11 + 2]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad2
        lea       r8, [r11 + 3]
        cmp       r8, r10
        jae       w_bad3
        movzx     r8d, byte ptr [r9 + r11 + 3]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad3
        add       eax, 2                            ; a complete four-byte sequence is a PAIR
        add       r11, 4

w_test: mov       rcx, r10
        sub       rcx, r11
        cmp       rcx, 32
        jae       w_fast                            ; thirty-two left: try them as a block
        cmp       r11, r10
        jb        w_loop
        add       eax, eax                          ; units -> BYTES of UTF-16
        mov       r8, qword ptr [rsp + 16]
        mov       dword ptr [r8], eax
        xor       eax, eax
        cmp       dword ptr [rsp + 8], 0
        je        w_ret
        mov       eax, 107h                         ; STATUS_SOME_NOT_MAPPED
w_ret:  vzeroupper
        ret

wia_u82u ENDP
END
