; changes/034-rtlutf8tounicoden/impl.asm
; NTSTATUS wia_u82u(wchar_t* dst, ulong maxBytes, pulong outLen, const void* src, ulong srcBytes)
;   [Win64: rcx, edx, r8, r9, [rsp+0x28] -> eax; *outLen = bytes produced]
;
; Reimplements ntdll!RtlUTF8ToUnicodeN (UTF-8 -> UTF-16). Full decoder validated
; in C against the live ntdll oracle (0 mismatches / 400000, incl. every malformed
; class). Malformed input follows the Unicode maximal-subpart rule with ntdll's
; twist: a byte-2 that is a generic continuation (0x80-0xBF) but out of the lead's
; special range is consumed (1 FFFD, advance 2); a non-continuation byte-2 is not.
; Status: 0, 0x107 STATUS_SOME_NOT_MAPPED, or 0xC0000023 STATUS_BUFFER_TOO_SMALL.
;
; ------------------------------------------------------------------------------
; a NULL destination is the measuring mode, added 2026-09-16 -- it was missing.
;
; RtlUTF8ToUnicodeN(NULL, 0, &produced, src, srcLen) is the documented way to ask
; this function how many bytes of UTF-16 the output will need: the shipped export
; returns STATUS_SUCCESS with `produced` set and writes nothing. This
; implementation returned STATUS_BUFFER_TOO_SMALL with produced = 0, and with a
; NULL pointer and a NON-ZERO size it dereferenced the pointer and faulted.
; discovery/utf8n_null_destination.c is the evidence; change 016 had the same gap
; and is corrected in the same way.
;
; Why the gates did not catch it: this change is bit-exact against the live export
; over 400000 cases including every malformed class, and every one of them passes
; a real destination buffer. A NULL destination is not an edge of the LENGTH,
; which is what the corpora sweep -- it is a different MODE of the same function.
;
; The counting rule is the one this decoder already implements, stated in the
; paragraph above and now also counted without converting: a stray continuation
; or an invalid lead is one unit and one byte; a lead whose byte-2 is not a
; continuation at all is one unit and one byte; a lead whose byte-2 IS a
; continuation but outside that lead's special range is one unit and TWO bytes;
; a truncated-but-valid prefix is one unit and however many bytes it had; and a
; complete four-byte sequence is TWO units. It was verified against the live
; measuring mode over 400000 random strings -- ASCII, continuation runs, lead
; runs, fully random bytes and valid UTF-8 -- with ZERO disagreements on the size
; AND on the status, before any of it was written in assembly.
; ------------------------------------------------------------------------------
;
; ISA: AVX2 + BMI1 + BMI2 (PDEP/POPCNT). Validated on Zen3.

.const
ALIGN 16
CQMASKw DW      8 dup(0C0E0h)                      ; per word: lead & 0xE0, continuation & 0xC0
CQWANTw DW      8 dup(080C0h)                      ; ... must be 0xC0 and 0x80
CQ1Ew   DW      16 dup(001Eh)                      ; the lead bits that separate C2..DF from C0/C1
CQDECw  DW      8 dup(3F1Fh)                       ; per word: lead & 0x1F, continuation & 0x3F
CQMULb  DB      8 dup(40h, 01h)                    ; VPMADDUBSW: lead*0x40 + continuation
; the three-byte block: one 3-byte sequence per 32-bit lane, the same pattern in both 128-bit lanes
CQ3SHUF DB      0,1,2,80h, 3,4,5,80h, 6,7,8,80h, 9,10,11,80h
        DB      0,1,2,80h, 3,4,5,80h, 6,7,8,80h, 9,10,11,80h
CQ3MSKd DD      8 dup(00C0C0F0h)                   ; lead & 0xF0, both continuations & 0xC0
CQ3WNTd DD      8 dup(008080E0h)                   ; ... must be 0xE0, 0x80, 0x80
CQ0Fd   DD      8 dup(0000000Fh)                   ; the lead's low nibble: 0 is E0, D is ED
CQ0Dd   DD      8 dup(0000000Dh)
CQ3Fd   DD      8 dup(0000003Fh)
; the four-byte block: a 4-byte sequence IS a 32-bit lane, so nothing has to be spread
CQ4MSKd DD      4 dup(0C0C0C0FCh)                  ; lead & 0xFC, all three continuations & 0xC0
CQ4WNTd DD      4 dup(808080F0h)                   ; ... must be 0xF0 and three 0x80s
CQ03d   DD      4 dup(00000003h)                   ; the lead's low two bits: 0 is F0
CQ30d   DD      4 dup(00003000h)                   ; byte 2's 0x30 bits: zero means 0x80..0x8F
CQ07d   DD      4 dup(00000007h)
CQ3FFd  DD      4 dup(000003FFh)
CQ10000d DD     4 dup(00010000h)
CQD800d DD      4 dup(0000D800h)
CQDC00d DD      4 dup(0000DC00h)
; the mixed block: one BYTE per 16-bit lane, so a lead and its continuation can be seen together
CQE0w   DW      16 dup(00E0h)
CQC0w   DW      16 dup(00C0h)
CQ80w   DW      16 dup(0080h)
CQ1Fw   DW      16 dup(001Fh)
CQ3Fw   DW      16 dup(003Fh)

; -------------------------------------------------------------------------------------------------
; The compaction table for the mixed block, generated by the assembler rather than pasted in.
;
; Eight input positions produce between four and eight UTF-16 units, depending on how many of them
; are continuation bytes belonging to the position before. Each position's unit is computed in its
; own 16-bit lane and the lanes are then compacted by one VPSHUFB, so the only thing that varies is
; the shuffle -- 256 of them, one per combination of which positions are KEPT.
;
; A kept position contributes its two bytes; a continuation contributes nothing, because its
; character was already produced by the lead before it. correctness.c checks every entry against
; the same rule written in C.
; -------------------------------------------------------------------------------------------------
ALIGN 16
MIXTAB LABEL BYTE
PKI = 0
REPT 256
    PKN = 0
    PKJ = 0
    REPT 8
        IF (PKI SHR PKJ) AND 1
            DB (2*PKJ)
            DB (2*PKJ)+1
            PKN = PKN + 2
        ENDIF
        PKJ = PKJ + 1
    ENDM
    REPT 16 - PKN
        DB 80h
    ENDM
    PKI = PKI + 1
ENDM

PUBLIC wia_u82u_mix_table

.code

; correctness.c calls this to check the assembler-generated table against the same rule in C
wia_u82u_mix_table PROC
        lea       rax, [MIXTAB]
        ret
wia_u82u_mix_table ENDP

wia_u82u PROC
        test      rcx, rcx
        jz        u82u_measure                      ; a NULL destination asks for the SIZE only
        push      rbx
        push      rsi
        push      rdi
        push      r12
        push      r13
        push      r14
        push      r15
        mov       rbx, rcx                          ; dst (wchar)
        shr       edx, 1
        mov       edi, edx                          ; maxWchars = maxBytes/2
        mov       r12, r8                           ; outLen ptr
        mov       rsi, r9                           ; src (utf8)
        mov       r13d, dword ptr [rsp + 60h]       ; srcBytes
        sub       rsp, 16
        mov       dword ptr [rsp], 0                ; notMapped
        mov       dword ptr [rsp+4], 0              ; overflow
        xor       r14, r14                          ; i (src index)
        xor       r15, r15                          ; o (dst wchar index)

mainloop:
        cmp       r14d, r13d
        jae       done
        ; ---- ASCII fast path: 16 bytes all < 0x80, room for 16 wchars ----
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        ascii8
        lea       eax, [r15 + 16]
        cmp       eax, edi
        ja        ascii8
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovmskb eax, xmm0
        test      eax, eax
        jnz       ascii8
        vpmovzxbw ymm0, xmm0
        vmovdqu   ymmword ptr [rbx + r15*2], ymm0
        add       r14, 16
        add       r15, 16
        jmp       mainloop
ascii8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 8
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        dispatch                          ; NOT scalar_win: if this hands the tight-room
                                                    ; case straight to the scalar path, every block
                                                    ; below inherits a room guarantee it never asked
                                                    ; for, and its own guard becomes a check that
                                                    ; cannot fail. Each block tests its own room.
        vmovq     xmm0, qword ptr [rsi + r14]
        vpmovmskb eax, xmm0
        and       eax, 0FFh
        jnz       dispatch
        vpmovzxbw xmm0, xmm0
        vmovdqu   xmmword ptr [rbx + r15*2], xmm0
        add       r14, 8
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; The dispatch: One byte decides which block, instead of trying them in turn.
;
; There are four vector blocks below and they are mutually exclusive: a run of two-byte sequences is
; not a run of three-byte ones. Chained, the block that finally matches is reached only after every
; earlier one has loaded, tested and declined -- which cost `mixed` input, the last block in the
; chain, about eighteen wasted instructions per eight characters, a third of its total.
;
; The byte at the current position already says which block can possibly apply, because it is the
; LEAD of the next character. Five comparisons replace three failed probes, and a stray
; continuation or an overlong lead -- which no block decodes -- goes straight to the scalar path
; instead of being discovered three blocks later.
; -------------------------------------------------------------------------------------------------
dispatch:
        movzx     eax, byte ptr [rsi + r14]
        cmp       eax, 80h
        jb        mix16                             ; ASCII here, something else nearby
        cmp       eax, 0C2h
        jb        scalar_win                        ; a stray continuation, or 0xC0 / 0xC1
        cmp       eax, 0E0h
        jb        two8
        cmp       eax, 0F0h
        jb        three8
        cmp       eax, 0F5h
        jb        four8
        jmp       scalar_win                        ; 0xF5..0xFF is never a lead

; -------------------------------------------------------------------------------------------------
; The two-byte block: Sixteen bytes, eight characters, no shuffle.
;
; discovery/utf8_nonascii_rows.c measured this decoder at 0.36x to 0.60x on every class of input
; that is not ASCII, after e71db44 had already removed the vector re-entry that was costing it a
; second time over. What was left was a missing kernel: the ASCII blocks above handle the one case
; where every byte is one character, and everything else walked one character at a time.
;
; A run of two-byte sequences is the easiest of the remaining cases and the commonest in Latin-1
; supplement, Greek, Cyrillic, Hebrew and Arabic text: sixteen bytes are exactly eight characters,
; a fixed count, so there is nothing to compact and no table to index.
;
; The validity test is two comparisons. Viewed as 16-bit words the input is [lead, continuation]
; per character, little-endian, so ANDing with 0xC0E0 and comparing against 0x80C0 says in one
; VPCMPEQW that every even byte is 0xC0..0xDF and every odd byte is 0x80..0xBF -- the whole
; structure of a two-byte run, tested in one instruction. The second comparison excludes 0xC0 and
; 0xC1, the overlong leads, which are the only bytes in 0xC0..0xDF whose low five bits are zero and
; which this decoder substitutes rather than decodes.
;
; And the arithmetic is one instruction. Vpmaddubsw multiplies unsigned bytes by signed bytes and
; sums adjacent pairs, so masking with 0x3F1F and multiplying by [0x40, 0x01] IS
; (lead & 0x1F) * 64 + (continuation & 0x3F), which is the code point. The largest value it can
; produce is 0x7FF, so there is no saturation to think about.
; -------------------------------------------------------------------------------------------------
ALIGN 16
two8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpand     xmm1, xmm0, xmmword ptr [CQMASKw]
        vpcmpeqw  xmm1, xmm1, xmmword ptr [CQWANTw]
        vpmovmskb eax, xmm1
        cmp       eax, 0FFFFh
        jne       mix16                             ; not eight clean two-byte sequences
        vpand     xmm1, xmm0, xmmword ptr [CQ1Ew]
        vpxor     xmm2, xmm2, xmm2
        vpcmpeqw  xmm1, xmm1, xmm2
        vpmovmskb eax, xmm1
        test      eax, eax
        jnz       mix16                             ; a 0xC0 or 0xC1 lead: overlong, not decoded
        vpand     xmm1, xmm0, xmmword ptr [CQDECw]
        vpmaddubsw xmm1, xmm1, xmmword ptr [CQMULb]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 16
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; The three-byte block: Twenty-four bytes, eight characters.
;
; Three-byte sequences are every CJK character, every arrow, dash, quotation mark and currency sign
; above U+0800, and -- because this decoder substitutes u+fffd, which is itself ef bf bd -- the
; output of every malformed run that has already been substituted once. They were 0.37x.
;
; Twenty-four bytes is eight sequences, a fixed count, so again there is nothing to compact. What
; three does that two did not is that it divides neither 16 nor 32, so the bytes have to be SPREAD
; before they can be worked on: one VPSHUFB puts each three-byte group into its own 32-bit lane,
; with the same pattern in both halves of the register. The two halves are loaded twelve bytes
; apart -- VPSHUFB cannot cross a 128-bit lane, so the second load starts where the first lane's
; four sequences end -- which is why this block reads 28 bytes to consume 24.
;
; After that the tests are single instructions again. ANDing a lane with 0x00C0C0F0 and comparing
; against 0x008080E0 says the lead is 0xE0..0xEF and both continuations are 0x80..0xBF. The lead's
; low nibble then excludes 0xE0 and 0xED, the two leads whose SECOND byte has a narrower range than
; 0x80..0xBF -- 0xE0 forbids the overlong forms and 0xED forbids the encoded surrogates, and this
; decoder substitutes both. Sending those two leads to the scalar path costs one sixteenth of the
; three-byte space and buys a validity test that is three instructions instead of a table.
; -------------------------------------------------------------------------------------------------
ALIGN 16
three8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 28                           ; 24 consumed, 28 read: see above
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vinserti128 ymm0, ymm0, xmmword ptr [rsi + r14 + 12], 1
        vpshufb   ymm0, ymm0, ymmword ptr [CQ3SHUF] ; one sequence per 32-bit lane
        vpand     ymm1, ymm0, ymmword ptr [CQ3MSKd]
        vpcmpeqd  ymm1, ymm1, ymmword ptr [CQ3WNTd]
        vpmovmskb eax, ymm1
        cmp       eax, -1
        jne       scalar_win                        ; not eight clean three-byte sequences
        vpand     ymm1, ymm0, ymmword ptr [CQ0Fd]
        vpxor     ymm2, ymm2, ymm2
        vpcmpeqd  ymm2, ymm1, ymm2                  ; lead 0xE0
        vpcmpeqd  ymm1, ymm1, ymmword ptr [CQ0Dd]   ; lead 0xED
        vpor      ymm1, ymm1, ymm2
        vpmovmskb eax, ymm1
        test      eax, eax
        jnz       scalar_win                        ; those two leads have narrower second bytes

        vpand     ymm1, ymm0, ymmword ptr [CQ0Fd]
        vpslld    ymm1, ymm1, 12                    ; the lead's four bits
        vpsrld    ymm2, ymm0, 8
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fd]
        vpslld    ymm2, ymm2, 6                     ; the first continuation
        vpor      ymm1, ymm1, ymm2
        vpsrld    ymm2, ymm0, 16
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fd]
        vpor      ymm1, ymm1, ymm2                  ; the second continuation
        vpackusdw ymm1, ymm1, ymm1
        vpermq    ymm1, ymm1, 8                     ; lane 0's four, then lane 1's four
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 24
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; The four-byte block: Sixteen bytes, four sequences, eight UTF-16 units.
;
; A four-byte sequence IS a 32-bit lane, so unlike the three-byte block nothing has to be spread:
; sixteen bytes are four sequences exactly, and four surrogate pairs are exactly sixteen bytes out.
; This is the emoji and supplementary-plane path, and it was 0.52x.
;
; The validity test is the same single comparison as the other blocks -- AND with 0xC0C0C0FC,
; compare against 0x808080F0 -- which says the lead is 0xF0..0xF3 and all three continuations are
; 0x80..0xBF. Excluding lead 0xF0 then takes one more test on its low two bits, and leaves this
; block covering U+40000..U+FFFFF. The two leads it does not take are the two with narrower second
; bytes: 0xF0 forbids the overlong forms below U+10000 and 0xF4 stops at U+10FFFF. Both go to the
; scalar path, which substitutes exactly what the shipped decoder substitutes.
;
; The surrogate split is the only part that is not shared with the other blocks, and it is four
; instructions: a code point above 0x10000 becomes 0xD800 + (v >> 10) and 0xDC00 + (v & 0x3FF),
; and the pair is assembled as ONE 32-bit lane -- high surrogate in the low half, low surrogate in
; the high half -- so that a plain store puts them in the right order.
; -------------------------------------------------------------------------------------------------
ALIGN 16
four8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpand     xmm1, xmm0, xmmword ptr [CQ4MSKd]
        vpcmpeqd  xmm1, xmm1, xmmword ptr [CQ4WNTd]
        vpmovmskb eax, xmm1
        cmp       eax, 0FFFFh
        jne       scalar_win                        ; not four clean four-byte sequences
        ; 0xF0 Is the commonest four-byte lead, not a corner to skip: it carries U+10000 through
        ; U+3FFFF, which is every emoji there is. The first draft of this block excluded it to keep
        ; the test to one comparison, and the emoji rows did not move at all -- 0.53x before and
        ; 0.53x after, because the block was never entered. What 0xF0 actually needs is one extra
        ; condition on its SECOND byte: 0x80..0x8F would encode a value below U+10000, which is
        ; overlong, and every second byte in 0x80..0x8F is exactly the one with no 0x30 bits set.
        vpand     xmm1, xmm0, xmmword ptr [CQ03d]
        vpxor     xmm2, xmm2, xmm2
        vpcmpeqd  xmm1, xmm1, xmm2                  ; the lead is 0xF0
        vpand     xmm2, xmm0, xmmword ptr [CQ30d]   ; the mask sits where byte 2 already is
        vpxor     xmm3, xmm3, xmm3
        vpcmpeqd  xmm2, xmm2, xmm3                  ; ... and its second byte is 0x80..0x8F
        vpand     xmm1, xmm1, xmm2
        vpmovmskb eax, xmm1
        test      eax, eax
        jnz       scalar_win                        ; an overlong four-byte sequence

        vpand     xmm1, xmm0, xmmword ptr [CQ07d]
        vpslld    xmm1, xmm1, 18                    ; the lead's three bits
        vpsrld    xmm2, xmm0, 8
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpslld    xmm2, xmm2, 12
        vpor      xmm1, xmm1, xmm2
        vpsrld    xmm2, xmm0, 16
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpslld    xmm2, xmm2, 6
        vpor      xmm1, xmm1, xmm2
        vpsrld    xmm2, xmm0, 24
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fd]
        vpor      xmm1, xmm1, xmm2                  ; the code point
        vpsubd    xmm1, xmm1, xmmword ptr [CQ10000d]
        vpsrld    xmm2, xmm1, 10
        vpaddd    xmm2, xmm2, xmmword ptr [CQD800d] ; the high surrogate
        vpand     xmm1, xmm1, xmmword ptr [CQ3FFd]
        vpaddd    xmm1, xmm1, xmmword ptr [CQDC00d]
        vpslld    xmm1, xmm1, 16                    ; the low surrogate, above it
        vpor      xmm1, xmm1, xmm2
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r14, 16
        add       r15, 8
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; The mixed block: ASCII and two-byte sequences together, eight positions at a time.
;
; Every block above needs its eight or twenty-four bytes to be the SAME KIND of sequence, and that
; is the one thing real text never is. `mixed` -- ASCII alternating with two-byte letters, which is
; what Greek, Cyrillic, Hebrew, Arabic or accented Latin prose looks like once it has spaces and
; punctuation in it -- went through every one of those blocks, failed all of them, and walked one
; character at a time: 0.42x, the last class short of the shipped decoder and the commonest
; non-ASCII input there is.
;
; This block does not need the positions to agree. One BYTE per 16-bit lane, and a second copy of
; the same bytes shifted down by one, so each lane can see both a byte and the byte after it. Then:
;
;   * anything at 0xE0 or above ends the block -- three- and four-byte sequences have their own;
;   * 0xC0 and 0xC1 end it, because this decoder substitutes the overlong forms rather than
;     decoding them;
;   * the STRUCTURE is one comparison of two eight-bit masks: the set of positions holding a lead
;     must equal the set of positions whose NEXT byte is a continuation. That single CMP says every
;     lead is followed by its continuation AND that no continuation is stranded -- and one more bit
;     test says position 0 is not itself a continuation, which would belong to a character that
;     ended before this block began.
;
; What is left is a lane per position holding either the ASCII character or the decoded two-byte
; value, and a VPSHUFB indexed by the eight-bit mask of positions that are NOT continuations
; compacts them. POPCNT of that same mask is how many units came out; a lead in the LAST position
; means its continuation was the ninth byte, so nine were consumed rather than eight.
; -------------------------------------------------------------------------------------------------
; -------------------------------------------------------------------------------------------------
; The mixed block, sixteen positions at a time.
;
; The eight-position version below is the same idea and took `mixed` from 0.42x to 0.84x; with the
; dispatch above removing the failed probes it reached 0.98x, which is a tie and is not a margin
; worth publishing. What is left is setup: classifying eight positions costs about as much as
; classifying sixteen, and eight positions of alternating ASCII and two-byte text yield only six
; UTF-16 units, so more than half the work was overhead.
;
; Sixteen positions are classified in one 256-bit pass and then compacted as TWO halves, because the
; compaction table is indexed by eight bits and VPSHUFB cannot cross a 128-bit lane anyway. PEXT
; turns each VPMOVMSKB result -- two identical bits per 16-bit lane -- into the one-bit-per-position
; mask the tests and the table want.
;
; Everything else is exactly the eight-position rule: nothing at 0xE0 or above, no 0xC0 or 0xC1, the
; set of positions holding a lead equals the set whose next byte is a continuation, and position 0
; is not itself a continuation. Seventeen bytes are read to consume at most seventeen.
; -------------------------------------------------------------------------------------------------
ALIGN 16
mix16:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 32
        jb        mix8
        lea       eax, [r15 + 16]
        cmp       eax, edi
        ja        mix8
        mov       r11d, 55555555h                   ; PEXT: one bit per 16-bit lane
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovzxbw ymm1, xmm0                        ; the bytes at 0..15
        vmovdqu   xmm2, xmmword ptr [rsi + r14 + 1]
        vpmovzxbw ymm2, xmm2                        ; the bytes at 1..16

        vpand     ymm3, ymm1, ymmword ptr [CQE0w]
        vpcmpeqw  ymm4, ymm3, ymmword ptr [CQC0w]   ; a lead, 0xC0..0xDF
        vpcmpeqw  ymm3, ymm3, ymmword ptr [CQE0w]   ; 0xE0 or above
        vpmovmskb eax, ymm3
        test      eax, eax
        jnz       mix8

        vpand     ymm3, ymm1, ymmword ptr [CQ1Ew]
        vpxor     ymm5, ymm5, ymm5
        vpcmpeqw  ymm3, ymm3, ymm5
        vpand     ymm3, ymm3, ymm4                  ; a lead whose low bits are zero: 0xC0 or 0xC1
        vpmovmskb eax, ymm3
        test      eax, eax
        jnz       mix8

        vpand     ymm3, ymm1, ymmword ptr [CQC0w]
        vpcmpeqw  ymm3, ymm3, ymmword ptr [CQ80w]   ; a continuation, at 0..15
        vpand     ymm5, ymm2, ymmword ptr [CQC0w]
        vpcmpeqw  ymm5, ymm5, ymmword ptr [CQ80w]   ; a continuation, at 1..16
        vpmovmskb eax, ymm5
        pext      r8d, eax, r11d
        vpmovmskb eax, ymm4
        pext      edx, eax, r11d
        cmp       r8d, edx
        jne       mix8                              ; a lead without its continuation, or the reverse
        vpmovmskb eax, ymm3
        pext      ecx, eax, r11d
        ; The first position is a character start, and the dispatch above is the one place that
        ; says so: it sends every byte below 0xC2 that is not ASCII straight to the scalar path.
        ; An earlier draft tested it again here and in the eight-position block below, which looked
        ; careful and was not -- the test could never fail, so the mutation that BREAKS the
        ; dispatch was caught by nothing and reported as harmless. One live check beats two dead
        ; ones.

        vpand     ymm5, ymm1, ymmword ptr [CQ1Fw]
        vpsllw    ymm5, ymm5, 6
        vpand     ymm2, ymm2, ymmword ptr [CQ3Fw]
        vpor      ymm5, ymm5, ymm2                  ; the two-byte value
        vpblendvb ymm1, ymm1, ymm5, ymm4            ; a lead's lane takes it; ASCII keeps itself

        not       ecx                               ; the positions that are NOT continuations
        lea       r10, [MIXTAB]
        mov       r9d, ecx
        and       r9d, 0FFh
        popcnt    eax, r9d
        shl       r9d, 4
        vpshufb   xmm3, xmm1, xmmword ptr [r10 + r9]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm3
        add       r15, rax
        vextracti128 xmm3, ymm1, 1
        shr       ecx, 8
        and       ecx, 0FFh
        popcnt    eax, ecx
        shl       ecx, 4
        vpshufb   xmm3, xmm3, xmmword ptr [r10 + rcx]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm3
        add       r15, rax
        shr       edx, 15                           ; a lead in the last position took a 17th byte
        and       edx, 1
        add       r14, 16
        add       r14, rdx
        jmp       mainloop

ALIGN 16
mix8:
        mov       eax, r13d
        sub       eax, r14d
        cmp       eax, 16                           ; at most 9 consumed; 16 read in one go
        jb        scalar_win
        lea       eax, [r15 + 8]
        cmp       eax, edi
        ja        scalar_win
        vmovdqu   xmm0, xmmword ptr [rsi + r14]
        vpmovzxbw xmm1, xmm0                        ; the bytes at 0..7
        vpsrldq   xmm2, xmm0, 1
        vpmovzxbw xmm2, xmm2                        ; the bytes at 1..8

        vpand     xmm3, xmm1, xmmword ptr [CQE0w]
        vpcmpeqw  xmm4, xmm3, xmmword ptr [CQC0w]   ; a lead, 0xC0..0xDF
        vpcmpeqw  xmm3, xmm3, xmmword ptr [CQE0w]   ; 0xE0 or above
        vpmovmskb eax, xmm3
        test      eax, eax
        jnz       scalar_win

        vpand     xmm3, xmm1, xmmword ptr [CQ1Ew]
        vpxor     xmm5, xmm5, xmm5
        vpcmpeqw  xmm3, xmm3, xmm5
        vpand     xmm3, xmm3, xmm4                  ; a lead whose low bits are zero: 0xC0 or 0xC1
        vpmovmskb eax, xmm3
        test      eax, eax
        jnz       scalar_win

        vpand     xmm3, xmm1, xmmword ptr [CQC0w]
        vpcmpeqw  xmm3, xmm3, xmmword ptr [CQ80w]   ; a continuation, at 0..7
        vpand     xmm5, xmm2, xmmword ptr [CQC0w]
        vpcmpeqw  xmm5, xmm5, xmmword ptr [CQ80w]   ; a continuation, at 1..8
        vpacksswb xmm5, xmm5, xmm5
        vpmovmskb r8d, xmm5
        and       r8d, 0FFh
        vpacksswb xmm5, xmm4, xmm4
        vpmovmskb edx, xmm5
        and       edx, 0FFh
        cmp       r8d, edx
        jne       scalar_win                        ; a lead without its continuation, or the reverse
        vpacksswb xmm5, xmm3, xmm3
        vpmovmskb ecx, xmm5
        ; the first position is a character start; see the note in the 16-position block above

        vpand     xmm5, xmm1, xmmword ptr [CQ1Fw]
        vpsllw    xmm5, xmm5, 6
        vpand     xmm2, xmm2, xmmword ptr [CQ3Fw]
        vpor      xmm5, xmm5, xmm2                  ; the two-byte value
        vpblendvb xmm1, xmm1, xmm5, xmm4            ; a lead's lane takes it; ASCII keeps itself

        not       ecx
        and       ecx, 0FFh                         ; the positions that are NOT continuations
        popcnt    eax, ecx
        lea       r10, [MIXTAB]
        shl       ecx, 4
        vpshufb   xmm1, xmm1, xmmword ptr [r10 + rcx]
        vmovdqu   xmmword ptr [rbx + r15*2], xmm1
        add       r15, rax
        shr       edx, 7                            ; a lead in the last position took a ninth byte
        and       edx, 1
        add       r14, 8
        add       r14, rdx
        jmp       mainloop

; -------------------------------------------------------------------------------------------------
; The scalar window, added 2026-09-16. Before it, every scalar character jumped back to `mainloop`
; and paid for both vector blocks again -- two loads, two VPMOVMSKBs and four comparisons -- to
; discover once more that the byte in front of it is not ASCII. On a string that is entirely
; two-byte sequences that cost was paid on every character for the whole string, and on input that
; alternates ASCII with non-ASCII it was paid twice per character. discovery/utf8_nonascii_rows.c
; measured what it came to: 0.33x to 0.48x against the shipped decoder on every class of input that
; is not ASCII, in a change published at 3.61x on input that is.
;
; This is change 263's rule, which this repository already wrote down and this file already broke:
; a scalar walk must not re-enter a vector loop. The window is the cheapest possible statement of
; it -- once the blocks have failed, 32 source bytes are decoded one character at a time before
; they are tried again, so the probe is amortised over a whole cache line of input instead of over
; one character. The two comparisons in `scalar_next` replace two vector loads.
; -------------------------------------------------------------------------------------------------
scalar_win:
        lea       eax, [r14 + 32]
        mov       dword ptr [rsp + 8], eax          ; decode this far before probing again

scalar:
        movzx     r8d, byte ptr [rsi + r14]         ; L
        cmp       r8d, 80h
        jb        sc_ascii
        cmp       r8d, 0C2h
        jb        sc_fffd1
        cmp       r8d, 0F5h
        jae       sc_fffd1
        ; expected length
        mov       r11d, 2
        cmp       r8d, 0E0h
        jb        have_exp
        mov       r11d, 3
        cmp       r8d, 0F0h
        jb        have_exp
        mov       r11d, 4
have_exp:
        ; byte-2 special range lo/hi
        mov       r9d, 80h
        mov       r10d, 0BFh
        cmp       r8d, 0E0h
        jne       chk_ED
        mov       r9d, 0A0h
        jmp       have_range
chk_ED:
        cmp       r8d, 0EDh
        jne       chk_F0
        mov       r10d, 9Fh
        jmp       have_range
chk_F0:
        cmp       r8d, 0F0h
        jne       chk_F4
        mov       r9d, 90h
        jmp       have_range
chk_F4:
        cmp       r8d, 0F4h
        jne       have_range
        mov       r10d, 8Fh
have_range:
        mov       ecx, 1                            ; consumed
        mov       edx, 1                            ; j
cons_loop:
        cmp       edx, r11d
        jae       cons_valid
        lea       eax, [r14 + rdx]
        cmp       eax, r13d
        jae       cons_invalid                      ; truncated
        movzx     eax, byte ptr [rsi + rax]         ; b
        cmp       eax, 80h
        jb        cons_invalid
        cmp       eax, 0BFh
        ja        cons_invalid
        inc       ecx
        cmp       edx, 1
        jne       cons_next
        cmp       eax, r9d
        jb        cons_invalid
        cmp       eax, r10d
        ja        cons_invalid
cons_next:
        inc       edx
        jmp       cons_loop

cons_invalid:
        mov       dword ptr [rsp], 1                ; notMapped
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], 0FFFDh
        inc       r15
        add       r14, rcx
        jmp       scalar_next

cons_valid:
        cmp       r11d, 2
        je        dec2
        cmp       r11d, 3
        je        dec3
        ; ---- 4-byte -> surrogate pair ----
        and       r8d, 7
        shl       r8d, 18
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        shl       eax, 12
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 2]
        and       eax, 3Fh
        shl       eax, 6
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 3]
        and       eax, 3Fh
        or        r8d, eax                          ; cp
        cmp       r15d, edi
        jae       ov_stop                           ; no room for high surrogate
        sub       r8d, 10000h
        mov       eax, r8d
        shr       eax, 10
        add       eax, 0D800h
        mov       word ptr [rbx + r15*2], ax        ; high surrogate
        inc       r15
        cmp       r15d, edi
        jae       ov_stop                           ; room for high only -> overflow
        mov       eax, r8d
        and       eax, 3FFh
        add       eax, 0DC00h
        mov       word ptr [rbx + r15*2], ax        ; low surrogate
        inc       r15
        add       r14, 4
        jmp       scalar_next
dec2:
        and       r8d, 1Fh
        shl       r8d, 6
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        or        r8d, eax
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], r8w
        inc       r15
        add       r14, 2
        jmp       scalar_next
dec3:
        and       r8d, 0Fh
        shl       r8d, 12
        movzx     eax, byte ptr [rsi + r14 + 1]
        and       eax, 3Fh
        shl       eax, 6
        or        r8d, eax
        movzx     eax, byte ptr [rsi + r14 + 2]
        and       eax, 3Fh
        or        r8d, eax
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], r8w
        inc       r15
        add       r14, 3
        jmp       scalar_next

sc_ascii:
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        movzx     eax, byte ptr [rsi + r14]
        mov       word ptr [rbx + r15*2], ax
        inc       r15
        inc       r14
        jmp       scalar_next
sc_fffd1:
        mov       dword ptr [rsp], 1
        lea       eax, [r15 + 1]
        cmp       eax, edi
        ja        ov_stop
        mov       word ptr [rbx + r15*2], 0FFFDh
        inc       r15
        inc       r14
        jmp       scalar_next
scalar_next:
        cmp       r14d, r13d
        jae       done                              ; the source is finished
        cmp       r14d, dword ptr [rsp + 8]
        jb        scalar                            ; still inside the window: stay scalar
        jmp       mainloop                          ; the window is spent: probe the blocks again

ov_stop:
        mov       dword ptr [rsp+4], 1

done:
        lea       eax, [r15*2]
        mov       dword ptr [r12], eax              ; *outLen = wchars*2
        mov       eax, dword ptr [rsp+4]
        test      eax, eax
        jnz       ret_small
        mov       eax, dword ptr [rsp]
        test      eax, eax
        jnz       ret_nm
        xor       eax, eax
        jmp       epi
ret_small:
        mov       eax, 0C0000023h
        jmp       epi
ret_nm:
        mov       eax, 107h
epi:
        add       rsp, 16
        vzeroupper
        pop       r15
        pop       r14
        pop       r13
        pop       r12
        pop       rdi
        pop       rsi
        pop       rbx
        ret
; ---------------------------------------------------------------------------------------------
; The measuring mode. Entered before the prologue, so it is a leaf: only the volatile registers
; and the caller's shadow space, which holds the two things there is no register left for.
;
;   r9 = src,  [rsp+40] = srcBytes,  [rsp+8] = notMapped,  [rsp+16] = the outLen pointer
;
; One byte at a time: this path is not the performance case, the conversion is.
; ---------------------------------------------------------------------------------------------
u82u_measure:
        mov       qword ptr [rsp + 16], r8          ; the outLen pointer, so r8 can be scratch
        mov       dword ptr [rsp + 8], 0            ; notMapped
        mov       r10d, dword ptr [rsp + 40]        ; srcBytes
        xor       r11d, r11d                        ; index
        xor       eax, eax                          ; units produced
        jmp       w_test

; The ASCII block, added 2026-09-16 because a caller measured it. The first version of this mode
; walked one byte at a time, which is the right shape for a path nothing calls in a loop -- and
; then change 268 called it on every allocating conversion and on every conversion into a tight
; destination, where the shipped code's own sizing pass is vectorised. On 4000 ASCII bytes that
; scalar walk cost more than the conversion it was sizing. Thirty-two bytes are tested at once
; here: VPMOVMSKB collects their top bits, and if none is set then all thirty-two are one UTF-16
; unit each and the count moves by 32 with no per-byte work. It needs no constant and no compare --
; the mask IS the answer. Anything else falls into the byte-at-a-time rule below, which is
; unchanged and still decides every multi-byte and every malformed case.
ALIGN 16
w_fast: vmovdqu   ymm0, ymmword ptr [r9 + r11]
        vpmovmskb ecx, ymm0
        test      ecx, ecx
        jnz       w_loop                            ; a byte with its top bit set: go carefully
        add       eax, 32
        add       r11, 32
        jmp       w_test
ALIGN 16
w_loop:
        movzx     ecx, byte ptr [r9 + r11]
        cmp       ecx, 80h
        jb        w_ascii
        cmp       ecx, 0C2h
        jb        w_bad1                            ; a stray continuation, or C0/C1
        cmp       ecx, 0E0h
        jb        w_two
        cmp       ecx, 0F0h
        jb        w_three
        cmp       ecx, 0F5h
        jb        w_four
        jmp       w_bad1                            ; F5..FF is never a lead

w_ascii:inc       eax
        inc       r11
        jmp       w_test
w_bad1: mov       dword ptr [rsp + 8], 1
        inc       eax
        inc       r11
        jmp       w_test
w_bad2: mov       dword ptr [rsp + 8], 1
        inc       eax
        add       r11, 2
        jmp       w_test
w_bad3: mov       dword ptr [rsp + 8], 1
        inc       eax
        add       r11, 3
        jmp       w_test

w_two:  lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1                            ; nothing follows the lead
        movzx     r8d, byte ptr [r9 + r11 + 1]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1                            ; what follows is not a continuation
        inc       eax
        add       r11, 2
        jmp       w_test

w_three:lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1
        movzx     edx, byte ptr [r9 + r11 + 1]
        mov       r8d, edx
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1                            ; not a continuation: consume ONE
        mov       r8d, 80h                          ; the lead's own lower bound
        cmp       ecx, 0E0h
        jne       w3lo
        mov       r8d, 0A0h
w3lo:   cmp       edx, r8d
        jb        w_bad2                            ; a continuation, but out of range: consume TWO
        mov       r8d, 0BFh
        cmp       ecx, 0EDh
        jne       w3hi
        mov       r8d, 9Fh
w3hi:   cmp       edx, r8d
        ja        w_bad2
        lea       r8, [r11 + 2]
        cmp       r8, r10
        jae       w_bad2
        movzx     r8d, byte ptr [r9 + r11 + 2]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad2
        inc       eax
        add       r11, 3
        jmp       w_test

w_four: lea       r8, [r11 + 1]
        cmp       r8, r10
        jae       w_bad1
        movzx     edx, byte ptr [r9 + r11 + 1]
        mov       r8d, edx
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad1
        mov       r8d, 80h
        cmp       ecx, 0F0h
        jne       w4lo
        mov       r8d, 90h
w4lo:   cmp       edx, r8d
        jb        w_bad2
        mov       r8d, 0BFh
        cmp       ecx, 0F4h
        jne       w4hi
        mov       r8d, 8Fh
w4hi:   cmp       edx, r8d
        ja        w_bad2
        lea       r8, [r11 + 2]
        cmp       r8, r10
        jae       w_bad2
        movzx     r8d, byte ptr [r9 + r11 + 2]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad2
        lea       r8, [r11 + 3]
        cmp       r8, r10
        jae       w_bad3
        movzx     r8d, byte ptr [r9 + r11 + 3]
        sub       r8d, 80h
        cmp       r8d, 40h
        jae       w_bad3
        add       eax, 2                            ; a complete four-byte sequence is a PAIR
        add       r11, 4

w_test: mov       rcx, r10
        sub       rcx, r11
        cmp       rcx, 32
        jae       w_fast                            ; thirty-two left: try them as a block
        cmp       r11, r10
        jb        w_loop
        add       eax, eax                          ; units -> BYTES of UTF-16
        mov       r8, qword ptr [rsp + 16]
        mov       dword ptr [r8], eax
        xor       eax, eax
        cmp       dword ptr [rsp + 8], 0
        je        w_ret
        mov       eax, 107h                         ; STATUS_SOME_NOT_MAPPED
w_ret:  vzeroupper
        ret

wia_u82u ENDP
END
