/* changes/273-inet-addr/correctness.c
 *
 * Gate 1 for ws2_32!inet_addr: Ours vs the scalar model vs the live export.
 *
 * There is only one thing to compare (the 32-bit result) so the whole weight of this gate is in
 * the corpus, and the corpus is built out of the four things the probes found that a plausible
 * generator would never produce:
 *
 *   * The overflow test is "did the accumulator go down" (probes/accum.c), so the corpus contains
 *     numbers with 9 to 24 digits in all three bases, with every leading digit, because whether one
 *     of those is accepted depends on a comparison between two wrapped values and nothing else.
 *   * Whitespace ends the address and the rest is ignored, so every one of the six whitespace bytes
 *     is placed at every position of several addresses, and every OTHER byte is placed there too,
 *     since "which bytes end it" is the question.
 *   * The single byte 0x20 is an address and nothing else with leading whitespace is.
 *   * Every part's field boundary, in all three bases, for all four forms.
 *
 * And a guard-page sweep, because the export reads a NUL-terminated string of unbounded length: a
 * string that ends exactly at an unmapped page is where a vectorised scan either stops in time or
 * faults.
 */
#define WIN32_LEAN_AND_MEAN
#include <winsock2.h>
#include <windows.h>
#include <stdio.h>
#include <string.h>

#pragma comment(lib, "ws2_32.lib")

extern unsigned long wia_inet_addr(const char*);
extern void* wia_inet_ctab(void);
unsigned long ref_inet_addr(const char*);

/* The class table is generated by REPT arithmetic, which is exactly the kind of thing that is wrong
   silently -- change 267's first table construction WAS wrong. So it is checked against the
   definition it is supposed to satisfy, computed the slow obvious way. */
static int check_table(void)
{
    const unsigned char* t = (const unsigned char*)wia_inet_ctab();
    int c, bad = 0;
    for (c = 0; c < 256; ++c) {
        unsigned char want = 0;
        if (c >= '0' && c <= '9')      want = (unsigned char)(0x10 + (c - '0'));
        else if (c >= 'a' && c <= 'f') want = (unsigned char)(0x10 + (c - 'a' + 10));
        else if (c >= 'A' && c <= 'F') want = (unsigned char)(0x10 + (c - 'A' + 10));
        else if (c == 9 || c == 10 || c == 11 || c == 12 || c == 13 || c == 32) want = 0x20;
        if (t[c] != want) {
            printf("  the class table is wrong at %02X: %02X, want %02X\n", c, t[c], want);
            ++bad;
        }
    }
    if (!bad) printf("  0. the assembler-generated class table matches its definition\n");
    return bad;
}

static int  failures = 0;
static long cases = 0;
static long n_ok = 0, n_none = 0;

static void one(const char* s)
{
    unsigned long a = wia_inet_addr(s);
    unsigned long b = inet_addr(s);
    unsigned long c = ref_inet_addr(s);
    ++cases;
    if (b == INADDR_NONE) ++n_none; else ++n_ok;
    if (a != b || a != c) {
        if (failures < 12) {
            int i;
            printf("  FAIL \"");
            for (i = 0; s[i] && i < 40; ++i)
                printf((unsigned char)s[i] >= 0x20 && (unsigned char)s[i] < 0x7F ? "%c" : "\\x%02X",
                       (unsigned char)s[i]);
            printf("\": ours %08lX  live %08lX  model %08lX\n",
                   (unsigned long)a, (unsigned long)b, (unsigned long)c);
        }
        ++failures;
    }
}

int main(void)
{
    WSADATA wd;
    SYSTEM_INFO si;
    static char s[4096];
    unsigned char* g_base;
    SIZE_T pagesz;
    int i, j, k;
    unsigned long seed = 1;

    setvbuf(stdout, NULL, _IONBF, 0);
    WSAStartup(MAKEWORD(2, 2), &wd);
    printf("== CORRECTNESS: inet_addr ==\n");
    if (check_table()) return 1;

    /* 1. every byte 0x01..0xFF in every position of several shapes */
    {
        long before = cases;
        static const char* FMT[] = {
            "%c1.2.3.4", "1.2.3.4%c", "1%c.2.3.4", "1.%c2.3.4", "1.2.3%c4", "1.2.3.4%c5",
            "%c", "1%c", "1.2%c", "1.2.3%c", "0%c", "0x%c", "0x1%c", "1.2.3.4 %c", "1.2.3.4%c ",
            "%c%c", "1%c%c"
        };
        for (j = 0; j < (int)(sizeof FMT / sizeof FMT[0]); ++j)
            for (i = 1; i <= 255; ++i) { wsprintfA(s, FMT[j], i, i); one(s); }
        printf("  1. every byte 0x01..0xFF in 17 positions: %ld\n", cases - before);
    }

    /* 2. the accumulator: 9..24 digits, every leading digit, all three bases */
    {
        long before = cases;
        static const char* PRE[] = { "", "0", "0x" };
        for (j = 0; j < 3; ++j)
            for (i = 0; i < 16; ++i) {
                for (k = 9; k <= 24; ++k) {
                    int n = 0, d;
                    n += wsprintfA(s + n, "%s", PRE[j]);
                    s[n++] = (char)(i < 10 ? '0' + i : 'A' + i - 10);
                    for (d = 1; d < k; ++d) s[n++] = (char)('0' + ((d * 7) % 10));
                    s[n] = 0;
                    one(s);
                    /* and the same as the last part of a four-part address */
                    { char t[64]; wsprintfA(t, "1.2.3.%s", s); one(t); }
                    { char t[64]; wsprintfA(t, "%s.2.3.4", s); one(t); }
                }
            }
        printf("  2. 9..24 digits, every leading digit, three bases, three positions: %ld\n",
               cases - before);
    }

    /* 3. every field boundary of every form, in every base */
    {
        long before = cases;
        static const unsigned long V[] = {
            0, 1, 7, 8, 9, 10, 15, 16, 127, 128, 254, 255, 256, 257,
            65534, 65535, 65536, 16777214, 16777215, 16777216,
            4294967294ul, 4294967295ul
        };
        static const char* FORM[] = { "%s", "1.%s", "1.2.%s", "1.2.3.%s", "%s.2.3.4", "%s.2", "%s.2.3" };
        char num[32];
        for (i = 0; i < (int)(sizeof V / sizeof V[0]); ++i) {
            const char* forms[3];
            char dec[32], oct[32], hex[32];
            wsprintfA(dec, "%lu", V[i]);
            { unsigned long v = V[i]; int n = 0; char t[32]; int m = 0;
              if (!v) t[m++] = '0';
              while (v) { t[m++] = (char)('0' + (v & 7)); v >>= 3; }
              oct[n++] = '0';
              while (m) oct[n++] = t[--m];
              oct[n] = 0; }
            wsprintfA(hex, "0x%lX", V[i]);
            forms[0] = dec; forms[1] = oct; forms[2] = hex;
            for (j = 0; j < 3; ++j)
                for (k = 0; k < (int)(sizeof FORM / sizeof FORM[0]); ++k) {
                    wsprintfA(s, FORM[k], forms[j]);
                    one(s);
                }
            (void)num;
        }
        printf("  3. every field boundary, three bases, seven forms: %ld\n", cases - before);
    }

    /* 4. the whitespace rules, exhaustively over position */
    {
        long before = cases;
        static const unsigned char WS[] = { 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20 };
        static const char* BASE[] = { "1.22.33.44", "1.2.3", "1.2", "1", "0x7f.1", "010.010" };
        for (j = 0; j < (int)(sizeof BASE / sizeof BASE[0]); ++j) {
            int n = (int)strlen(BASE[j]);
            for (i = 0; i < 6; ++i)
                for (k = 0; k <= n; ++k) {
                    int a, m = 0;
                    for (a = 0; a < k; ++a) s[m++] = BASE[j][a];
                    s[m++] = (char)WS[i];
                    for (a = k; a < n; ++a) s[m++] = BASE[j][a];
                    s[m] = 0;
                    one(s);
                    /* and with rubbish after the whitespace */
                    lstrcpyA(s + m, "junk");
                    one(s);
                }
        }
        printf("  4. six whitespace bytes at every position of six addresses: %ld\n",
               cases - before);
    }

    /* 5. leading zeros, which probes/bytes.c showed are unbounded */
    {
        long before = cases;
        for (k = 0; k <= 300; k += 7) {
            int n;
            for (n = 0; n < k; ++n) s[n] = '0';
            lstrcpyA(s + k, "1.2.3.4");
            one(s);
            for (n = 0; n < k; ++n) s[n] = '0';
            lstrcpyA(s + k, "12.2.3.4");
            one(s);
            lstrcpyA(s, "0x");
            for (n = 0; n < k; ++n) s[2 + n] = '0';
            lstrcpyA(s + 2 + k, "12345678");
            one(s);
        }
        printf("  5. up to 300 leading zeros, decimal and hexadecimal: %ld\n", cases - before);
    }

    /* 6. a string ending exactly at a guard page */
    {
        long before = cases;
        GetSystemInfo(&si);
        pagesz = si.dwPageSize;
        g_base = (unsigned char*)VirtualAlloc(0, pagesz * 2, MEM_RESERVE, PAGE_NOACCESS);
        if (!g_base || !VirtualAlloc(g_base, pagesz, MEM_COMMIT, PAGE_READWRITE)) {
            printf("  the guard page could not be set up\n"); return 1;
        }
        for (i = 0; i <= 200; ++i) {
            char* q = (char*)(g_base + pagesz - (i + 1));
            int m = wsprintfA(s, "1.22.333.4 junk and more text after it");
            for (k = 0; k < i; ++k) q[k] = (k < m) ? s[k] : (char)('0' + (k % 10));
            q[i] = 0;
            one(q);
        }
        printf("  6. every length 0..200 ending exactly at a guard page: %ld\n", cases - before);
    }

    /* 7. randomised, built from the alphabet the grammar actually uses */
    {
        long before = cases;
        for (i = 0; i < 300000 && failures < 12; ++i) {
            int len, m;
            seed = seed * 1103515245u + 12345u;
            len = 1 + (int)((seed >> 8) % 28);
            for (m = 0; m < len; ++m) {
                seed = seed * 1103515245u + 12345u;
                if (((seed >> 20) & 7) == 0) s[m] = (char)(1 + (seed >> 7) % 255);
                else s[m] = "0123456789.xX abcdefABCDEF\t"[(seed >> 7) % 27];
            }
            s[len] = 0;
            one(s);
        }
        printf("  7. 300000 randomised over the grammar's alphabet: %ld\n", cases - before);
    }

    /* 8. NULL */
    {
        unsigned long a, b, c;
        a = wia_inet_addr(0); b = inet_addr(0); c = ref_inet_addr(0);
        ++cases;
        if (a != b || a != c) {
            printf("  FAIL NULL: ours %08lX live %08lX model %08lX\n",
                   (unsigned long)a, (unsigned long)b, (unsigned long)c);
            ++failures;
        }
        printf("  8. the NULL argument: 1\n");
    }

    printf("\n  total cases: %ld,  mismatches: %d\n", cases, failures);
    printf("  the live export accepted %ld and refused %ld\n", n_ok, n_none);
    if (n_ok < 5000 || n_none < 5000) {
        printf("  the corpus did not reach both outcomes often enough\n");
        ++failures;
    }
    if (!failures)
        printf("CORRECTNESS: PASS (the 32-bit result exact vs live ws2_32 and vs the scalar model,\n"
               "including a string ending exactly at a guard page)\n");
    else
        printf("CORRECTNESS: FAIL (%d)\n", failures);
    return failures ? 1 : 0;
}
