; changes/273-inet-addr/impl.asm
;   unsigned long wia_inet_addr(const char* s)      [Win64: rcx -> eax, in NETWORK byte order]
;
; ws2_32!inet_addr, the LENIENT IPv4 parser. discovery/sid_inet_bstr.c measured it at 24.98 ns and
; flagged it as the one that takes "1.2", "0x7f.1" and octal -- all of which RtlIpv4StringToAddressA
; (change 114, already converted) REFUSES. probes/grammar.c confirmed the two disagree on six of ten
; hand-picked inputs, so this is not change 114 behind a wrapper and could not have been.
;
; --------------------------------------------------------------------------------------------------
; The grammar is the documented one. Four forms -- a.b.c.d, a.b.c (16-bit tail), a.b (24-bit tail),
; a (32 bits) -- and each part is decimal, octal after a leading `0`, or hexadecimal after `0x`. The
; base is decided PER PART, so `1.0x2.03.4` is legal, and the result comes back byte-swapped.
;
; Three things are not what the source everyone quotes does, and each was measured:
;
;   1. The overflow test is "did the accumulator go down" (probes/accum.c). The accumulator is 32
;      bits and wraps; a digit is refused only when the wrapped result is strictly less than the
;      value before it:
;
;          0x112345678   accepted, 0x12345678   -- the textbook check `acc > (MAX-d)/16` REFUSES it
;          0x212345678   refused                -- 0x12345678 < 0x21234567, so it went down
;          0x7FFFFFFF0   accepted, 0xFFFFFFF0   -- overflows 32 bits and is accepted anyway
;          12345678901   accepted, 0xDFDC1C35   -- wrapped, and larger than 1234567890
;          99999999999   refused                -- wrapped to something smaller
;
;      probes/accum.c swept all sixteen leading hexadecimal digits at nine and ten digits: accepted
;      if and only if the leading digit is 0 or 1, which is what this test predicts and no other
;      does. An implementation with the "correct" overflow check is wrong on inputs anyone could
;      type. It is `cmp edx, eax / jb fail` below, and it is one instruction.
;
;   2. Whitespace ends the address and everything after it is ignored -- once a digit has been
;      consumed. Any of 09 0A 0B 0C 0D 20 does it and the rest is never looked at: "1.2.3.4 junk" is
;      1.2.3.4, and "1 junk" is 0.0.0.1. LEADING whitespace is refused. probes/bytes.c swept every
;      byte in twelve positions to get that set rather than guessing at "isspace".
;
;   3. The single byte 0x20 is an address. `" "` -- one space and the terminator, nothing else --
;      comes back as 0.0.0.0. Two spaces do not, a tab does not, `" 1"` does not, `""` does not.
;      probes/lonespace.c asked from every side and no model of the grammar explains it. It is ONE
;      input out of all possible inputs and it is reproduced here, because bit-exactness is the
;      standard and a gate comparing against the live export would otherwise report it forever.
;
; And one ambiguity that is built in: INADDR_NONE is 0xFFFFFFFF, which is also the value of
; 255.255.255.255, so a refusal and that one address are indistinguishable -- here, in the live
; export, and to every caller. The last error is not set either way (probes/grammar.c).
;
; --------------------------------------------------------------------------------------------------
; ISA: baseline x64. There is nothing to vectorise in a four-number parse; what makes it fast is that
; every character costs ONE table load, and that the table answers "is this a digit in this base",
; "what is it worth" and "is it whitespace" at once. The table is generated by the assembler from
; the definition it is supposed to satisfy and checked back against it by correctness.c.
;
; No calls, nothing pushed in the body, so the unwind data is exact.

OPTION PROC:PRIVATE
PUBLIC wia_inet_addr
PUBLIC wia_inet_ctab                        ; so correctness.c can check the table

.const
ALIGN 16
; Bit 4 set means "a hexadecimal digit", and then the low nibble is its value -- so one load answers
; every base by comparing that nibble against 8, 10 or 16. Bit 5 set means "one of the six bytes
; that end an address".
CTAB    LABEL BYTE
        CI = 0
        REPT 256
          IF (CI GE '0') AND (CI LE '9')
            DB 10h + (CI - '0')
          ELSEIF (CI GE 'a') AND (CI LE 'f')
            DB 10h + (CI - 'a' + 10)
          ELSEIF (CI GE 'A') AND (CI LE 'F')
            DB 10h + (CI - 'A' + 10)
          ELSEIF (CI EQ 9) OR (CI EQ 10) OR (CI EQ 11) OR (CI EQ 12) OR (CI EQ 13) OR (CI EQ 32)
            DB 20h
          ELSE
            DB 0
          ENDIF
          CI = CI + 1
        ENDM

.code

FRAME_SZ  EQU 32                            ; the four parts; there are no calls, so no shadow space

ALIGN 16
wia_inet_addr PROC FRAME
        push      rbx
        .pushreg  rbx
        push      rsi
        .pushreg  rsi
        push      rdi
        .pushreg  rdi
        push      r12
        .pushreg  r12
        sub       rsp, FRAME_SZ
        .allocstack FRAME_SZ
        .endprolog

        test      rcx, rcx
        jz        fail                            ; measured: NULL is INADDR_NONE, not a fault
        mov       rsi, rcx
        lea       r8, CTAB

        ; The one special case, tested a byte at a time. a word-sized compare would read two bytes
        ; of a one-byte string, which faults when it ends a page -- and correctness.c puts strings
        ; against a guard page precisely to catch that.
        cmp       byte ptr [rsi], 20h
        jne       parse
        cmp       byte ptr [rsi + 1], 0
        je        ret_zero
parse:
        xor       edi, edi                        ; how many parts so far

part:
        movzx     eax, byte ptr [rsi]
        movzx     edx, byte ptr [r8 + rax]
        test      dl, 10h
        jz        fail                            ; a part must start with a digit ...
        mov       ecx, edx
        and       ecx, 0Fh
        cmp       ecx, 10
        jae       fail                            ; ... and a DECIMAL one: "0xff" is fine, "ff" is not
        mov       ebx, 10
        xor       eax, eax
        test      ecx, ecx
        jnz       digits                          ; a non-zero first digit: plain decimal

        ; it began with '0'
        inc       rsi
        movzx     ecx, byte ptr [rsi]
        or        ecx, 20h
        cmp       ecx, 'x'
        jne       octal
        inc       rsi
        mov       ebx, 16
        movzx     ecx, byte ptr [rsi]
        movzx     ecx, byte ptr [r8 + rcx]
        test      cl, 10h
        jz        fail                            ; "0x" on its own is not a number
        jmp       digits
octal:
        mov       ebx, 8                          ; the leading zero IS the digit, so a bare "0" is 0

digits:
        movzx     ecx, byte ptr [rsi]
        movzx     ecx, byte ptr [r8 + rcx]
        test      cl, 10h
        jz        part_done
        and       ecx, 0Fh
        cmp       ecx, ebx
        jae       part_done                       ; '8' ends an octal part; 'g' ends a hex one
        mov       edx, eax
        imul      edx, ebx
        add       edx, ecx                        ; the accumulator is 32 bits and WRAPS
        cmp       edx, eax
        jb        fail                            ; ... and this one instruction is rule 1
        mov       eax, edx
        inc       rsi
        jmp       digits

part_done:
        cmp       edi, 4
        jae       fail                            ; a fifth part
        mov       dword ptr [rsp + rdi*4], eax
        inc       edi
        cmp       byte ptr [rsi], '.'
        jne       term
        inc       rsi
        jmp       part

term:
        movzx     eax, byte ptr [rsi]
        test      eax, eax
        jz        pack                            ; the terminator
        movzx     edx, byte ptr [r8 + rax]
        test      dl, 20h
        jz        fail
        ; whitespace: the address ends here and the rest of the string is never looked at

pack:
        mov       eax, dword ptr [rsp]
        cmp       edi, 1
        je        fin                             ; one part: all 32 bits, nothing to check
        cmp       eax, 255
        ja        fail
        mov       ecx, dword ptr [rsp + 4]
        cmp       edi, 2
        je        pack2
        cmp       ecx, 255
        ja        fail
        mov       edx, dword ptr [rsp + 8]
        cmp       edi, 3
        je        pack3
        cmp       edx, 255
        ja        fail
        mov       r12d, dword ptr [rsp + 12]
        cmp       r12d, 255
        ja        fail
        shl       eax, 24
        shl       ecx, 16
        shl       edx, 8
        or        eax, ecx
        or        edx, r12d
        or        eax, edx
        jmp       fin
pack3:
        cmp       edx, 0FFFFh
        ja        fail
        shl       eax, 24
        shl       ecx, 16
        or        eax, ecx
        or        eax, edx
        jmp       fin
pack2:
        cmp       ecx, 0FFFFFFh
        ja        fail
        shl       eax, 24
        or        eax, ecx
fin:
        bswap     eax                             ; network byte order
        jmp       epi
ret_zero:
        xor       eax, eax
        jmp       epi
fail:
        mov       eax, 0FFFFFFFFh                 ; INADDR_NONE, which byte-swaps to itself
epi:
        add       rsp, FRAME_SZ
        pop       r12
        pop       rdi
        pop       rsi
        pop       rbx
        ret
wia_inet_addr ENDP

ALIGN 16
wia_inet_ctab PROC
        lea       rax, CTAB
        ret
wia_inet_ctab ENDP

END
