/* changes/281-strchriw/probes/gentable.c
 *
 * GENERATES foldpairs.c, the fold relation, asked of StrChrIW and written out.
 *
 * Every table in this project is built by asking the function that owns it, never transcribed:
 * change 277's case tables, change 269's SDDL aliases, change 210's upcase table. This one cannot
 * be built at init the way those are, and the reason is measured:
 *
 *   * asking StrChrIW directly costs 86.5 SECONDS (65535 calls over a 65535-character haystack),
 *     which is not something a gate can do on every run;
 *   * and the cheap shortcut does not work. probes/sortkey.c computed the whole relation from
 *     LCMapStringW(LCMAP_SORTKEY|NORM_IGNORECASE) in 0.002 s and it SPLITS 116 classes the export
 *     unites, all of them precomposed Hangul syllables against their jamo, U+AE4B against
 *     U+1101 and so on. Close is not the relation.
 *
 * So the relation is extracted ONCE, here, from the live export, and written out as source. What
 * keeps that honest is that the output is SMALL and CHECKABLE: 57063 of the 59321 classes are
 * singletons, so only 8472 code units are in a class with anybody else, and those are the only ones
 * that need to be written down. tables.c rebuilds the full 65536-entry map from those pairs at init
 * and then VERIFIES it against the live export in milliseconds; every non-singleton class is
 * checked by asking StrChrIW to find each of its members in a short string of the class.
 *
 * Run this only to regenerate foldpairs.c. The gate does not need it.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>

typedef PCWSTR (WINAPI *F_chr)(PCWSTR, WCHAR);
static F_chr chrI;
static wchar_t hay[65537];
static unsigned short rep[65536];
static unsigned short cnt[65536];

int main(void)
{
    HMODULE hs = LoadLibraryW(L"shlwapi.dll");
    unsigned c;
    LARGE_INTEGER t0, t1, fq;
    FILE* f;
    long pairs = 0, nonsingle = 0, biggest = 0;

    setvbuf(stdout, NULL, _IONBF, 0);
    QueryPerformanceFrequency(&fq);
    chrI = (F_chr)GetProcAddress(hs, "StrChrIW");
    if (!chrI) { printf("resolve failed\n"); return 1; }

    for (c = 1; c <= 0xFFFF; ++c) hay[c - 1] = (wchar_t)c;
    hay[0xFFFF] = 0;

    printf("asking StrChrIW for the canonical representative of all 65535 code units...\n");
    QueryPerformanceCounter(&t0);
    for (c = 1; c <= 0xFFFF; ++c) {
        PCWSTR p = chrI(hay, (WCHAR)c);
        rep[c] = p ? (unsigned short)(p - hay + 1) : (unsigned short)c;
    }
    QueryPerformanceCounter(&t1);
    printf("  %.1f s\n", (double)(t1.QuadPart - t0.QuadPart) / fq.QuadPart);

    for (c = 1; c <= 0xFFFF; ++c) ++cnt[rep[c]];
    for (c = 0; c <= 0xFFFF; ++c) {
        if (cnt[c] > 1) ++nonsingle;
        if (cnt[c] > biggest) biggest = cnt[c];
    }
    for (c = 1; c <= 0xFFFF; ++c) if (cnt[rep[c]] > 1) ++pairs;
    printf("  %ld non-singleton classes, %ld code units in them, largest %ld\n",
           nonsingle, pairs, biggest);

    f = fopen("../foldpairs.c", "w");
    if (!f) { printf("cannot write ../foldpairs.c\n"); return 1; }
    fprintf(f,
"/* changes/281-strchriw/foldpairs.c -- GENERATED by probes/gentable.c. Do not edit by hand.\n"
" *\n"
" * shlwapi!StrChrIW's fold relation, extracted from the LIVE export: for every code unit that\n"
" * shares a class with any other, the code unit and the smallest code unit in its class.\n"
" *\n"
" * Only %ld of the 65535 code units are in a class with anybody else -- %ld of the %ld classes are\n"
" * singletons -- so this is the whole relation and it fits in %ld pairs. The largest class has %ld\n"
" * members (U+00AD and the other ignorables).\n"
" *\n"
" * tables.c rebuilds the full map from these pairs and then CHECKS IT against the live export at\n"
" * init, in milliseconds. Asking the export for the whole relation directly takes 86.5 seconds,\n"
" * and the cheap shortcut through LCMapStringW sort keys splits 116 Hangul classes -- see\n"
" * probes/sortkey.c. That is why this file is generated rather than computed.\n"
" */\n"
"const unsigned short wia_sci_pairs[] = {\n", pairs, 57063L, 59321L, pairs, biggest);
    {
        long n = 0;
        for (c = 1; c <= 0xFFFF; ++c) {
            if (cnt[rep[c]] <= 1) continue;
            fprintf(f, "0x%04X,0x%04X,", c, rep[c]);
            if ((++n % 8) == 0) fprintf(f, "\n");
        }
        fprintf(f, "\n};\nconst unsigned wia_sci_npairs = %ld;\n", n);
        printf("  wrote ../foldpairs.c with %ld pairs\n", n);
    }
    fclose(f);
    return 0;
}
