/* changes/281-strchriw/probes/gentable2.c
 *
 * THE RELATION IS SYMMETRIC BUT NOT TRANSITIVE, SO IT HAS NO CLASSES.
 *
 * probes/gentable.c extracted a canonical representative per code unit and called the result
 * "classes". probes/context.c then proved the relation really is decided one character at a time --
 * 200000 random strings, 0 context-dependent matches -- and probes/isequiv.c proved it symmetric.
 * Both of those are necessary for a table. Neither is sufficient, and the missing one is the one
 * nothing checked:
 *
 *     U+D7B0 matches U+D7A2.     U+D7B1 matches U+D7A2.     U+D7B0 does NOT match U+D7B1.
 *
 * That is a TOLERANCE relation, not an equivalence relation. It has no classes, so "the members of
 * the needle's class" is not a well-defined object and every structure built on it is wrong. The
 * gate said so: 66 mismatches where OURS AGREED WITH LIVE and only the class-based model claimed a
 * match.
 *
 * What IS well defined is the MATCH SET OF A FIXED NEEDLE: S(n) = { w : StrChrIW finds w when
 * searching for n }. The implementation only ever needs S(needle), so indexing by needle instead of
 * by class fixes the design without changing the inner loop at all.
 *
 * gentable.c could not build that, because a haystack scan returns only the FIRST match. This
 * enumerates the WHOLE set: scan, record, resume past the hit, repeat. The relation is symmetric,
 * so the result is checked both ways as it is built.
 *
 * Writes foldsets.c.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>

typedef PCWSTR (WINAPI *F_chr)(PCWSTR, WCHAR);
static F_chr chrI;

static wchar_t hay[65537];
static unsigned short set[65536][8];      /* up to 8 partners per needle */
static unsigned char  nset[65536];
static unsigned char  over[65536];        /* more than 8: the implementation must fall back */

int main(void)
{
    HMODULE hs = LoadLibraryW(L"shlwapi.dll");
    unsigned c;
    LARGE_INTEGER t0, t1, fq;
    FILE* f;
    long total = 0, biggest = 0, nover = 0, nonself = 0, asym = 0, intrans = 0;

    setvbuf(stdout, NULL, _IONBF, 0);
    QueryPerformanceFrequency(&fq);
    chrI = (F_chr)GetProcAddress(hs, "StrChrIW");
    if (!chrI) { printf("resolve failed\n"); return 1; }

    for (c = 1; c <= 0xFFFF; ++c) hay[c - 1] = (wchar_t)c;
    hay[0xFFFF] = 0;

    printf("enumerating the FULL match set of every needle (not just the first hit)...\n");
    QueryPerformanceCounter(&t0);
    for (c = 1; c <= 0xFFFF; ++c) {
        PCWSTR p = hay;
        unsigned n = 0;
        for (;;) {
            p = chrI(p, (WCHAR)c);
            if (!p) break;
            if (n < 8) set[c][n] = (unsigned short)(p - hay + 1);
            ++n;
            ++p;
            if (!*p) break;
        }
        if (n > 8) { over[c] = 1; ++nover; }
        nset[c] = (unsigned char)(n > 8 ? 8 : n);
        total += n;
        if ((long)n > biggest) biggest = n;
        if (n != 1 || (n == 1 && set[c][0] != c)) ++nonself;
        if ((c & 0x1FFF) == 0) printf("   ... %u\n", c);
    }
    QueryPerformanceCounter(&t1);
    printf("   done in %.1f s\n", (double)(t1.QuadPart - t0.QuadPart) / fq.QuadPart);
    printf("   %ld matching pairs, largest set %ld, %ld needles with more than 8 partners,\n"
           "   %ld needles that match something other than exactly themselves\n",
           total, biggest, nover, nonself);

    /* symmetry, as a self-check on the extraction */
    for (c = 1; c <= 0xFFFF; ++c) {
        unsigned k;
        if (over[c]) continue;
        for (k = 0; k < nset[c]; ++k) {
            unsigned d = set[c][k], m, found = 0;
            if (over[d]) { found = 1; break; }
            for (m = 0; m < nset[d]; ++m) if (set[d][m] == c) { found = 1; break; }
            if (!found) ++asym;
        }
    }
    printf("   asymmetric entries: %ld  (must be 0)\n", asym);

    /* and how intransitive is it, really */
    for (c = 1; c <= 0xFFFF; ++c) {
        unsigned k, m;
        if (over[c] || nset[c] < 2) continue;
        for (k = 0; k < nset[c]; ++k)
            for (m = 0; m < nset[c]; ++m) {
                unsigned a = set[c][k], b = set[c][m], q, ok = 0;
                if (a == b || over[a]) continue;
                for (q = 0; q < nset[a]; ++q) if (set[a][q] == b) { ok = 1; break; }
                if (!ok) ++intrans;
            }
    }
    printf("   INTRANSITIVE triples: %ld  (two partners of one needle that do not match each\n"
           "   other -- this is why the relation has no classes)\n", intrans);

    f = fopen("../foldsets.c", "w");
    if (!f) { printf("cannot write ../foldsets.c\n"); return 1; }
    fprintf(f,
"/* changes/281-strchriw/foldsets.c -- GENERATED by probes/gentable2.c. Do not edit by hand.\n"
" *\n"
" * shlwapi!StrChrIW's match relation, extracted from the LIVE export by enumerating the FULL match\n"
" * set of every needle -- scan, record, resume past the hit, repeat.\n"
" *\n"
" * THE RELATION IS SYMMETRIC BUT NOT TRANSITIVE. U+D7B0 matches U+D7A2 and U+D7B1 matches U+D7A2,\n"
" * but U+D7B0 does not match U+D7B1. It is a tolerance relation, so it has NO CLASSES, and an\n"
" * earlier version of this table that grouped code units into classes was wrong -- the gate caught\n"
" * it in 66 cases out of 206096. What is well defined is the match set of a FIXED needle, which is\n"
" * the only thing the implementation ever needs.\n"
" *\n"
" * %ld matching pairs over 65535 needles; largest set %ld; %ld needles match something other than\n"
" * exactly themselves. Entries are (needle, count, up to 8 partners); a count of 255 means more\n"
" * than eight partners and the implementation must use its fallback path.\n"
" */\n"
"const unsigned short wia_sci_sets[] = {\n", total, biggest, nonself);
    {
        long rows = 0;
        for (c = 1; c <= 0xFFFF; ++c) {
            unsigned k;
            if (!over[c] && nset[c] == 1 && set[c][0] == c) continue;   /* matches only itself */
            fprintf(f, "0x%04X,%u,", c, over[c] ? 255u : nset[c]);
            for (k = 0; k < (over[c] ? 0u : nset[c]); ++k) fprintf(f, "0x%04X,", set[c][k]);
            fprintf(f, "\n");
            ++rows;
        }
        fprintf(f, "};\nconst unsigned wia_sci_nsets = %ld;\n", rows);
        printf("   wrote ../foldsets.c with %ld needle rows\n", rows);
    }
    fclose(f);
    return 0;
}
